// 初始化prompt数据集（示例数据）
const prompts = [
    { en: "2b_(nier:automata)", cn: "2B（尼尔：自动人形）" },
    { en: "35p_(sakura_miko)", cn: "35p（樱巫女）" },
    { en: "9s_(nier:automata)", cn: "9S（尼尔：自动人形）" },
    { en: "a2_(nier:automata)", cn: "A2（尼尔：自动人形）" },
    { en: "abe_nana", cn: "安倍奈奈" },
    { en: "abigail_williams_(fate)", cn: "阿比盖尔·威廉姆斯（命运）" },
    { en: "abigail_williams_(swimsuit_foreigner)_(fate)", cn: "阿比盖尔·威廉姆斯（泳装外国人）（命运）" },
    { en: "abigail_williams_(traveling_outfit)_(fate)", cn: "阿比盖尔·威廉姆斯（旅行服装）（命运）" },
    { en: "abukuma_(kancolle)", cn: "阿武隈（舰队收藏）" },
    { en: "acerola_(pokemon)", cn: "阿克罗拉（宝可梦）" },
    { en: "acheron_(honkai:_star_rail)", cn: "阿喀琉斯（崩坏：星穹铁道）" },
    { en: "adachi_rei", cn: "安达怜" },
    { en: "admire_vega_(umamusume)", cn: "仰慕织女（赛马娘）" },
    { en: "adventurer_(ff11)", cn: "冒险者（最终幻想11）" },
    { en: "aegir_(azur_lane)", cn: "埃吉尔（碧蓝航线）" },
    { en: "agnes_digital_(umamusume)", cn: "艾妮数字（赛马娘）" },
    { en: "ahri_(league_of_legends)", cn: "阿狸（英雄联盟）" },
    { en: "aida_mana", cn: "相田玛娜" },
    { en: "aino_minako", cn: "爱野美奈子" },
    { en: "air_groove_(umamusume)", cn: "空中舞蹈（赛马娘）" },
    { en: "airi_(blue_archive)", cn: "爱莉（蔚蓝档案）" },
    { en: "aisaka_taiga", cn: "逢坂大河" },
    { en: "ak-12_(girls'_frontline)", cn: "AK-12（少女前线）" },
    { en: "akagi_(azur_lane)", cn: "赤城（碧蓝航线）" },
    { en: "akagi_miria", cn: "赤城美里" },
    { en: "akai_haato", cn: "赤井心" },
    { en: "akali", cn: "阿卡丽" },
    { en: "akamatsu_kaede", cn: "赤松枫" },
    { en: "akane_(blue_archive)", cn: "茜（蔚蓝档案）" },
    { en: "akashi_(kancolle)", cn: "明石（舰队收藏）" },
    { en: "akatsuki_kirika", cn: "晓切歌" },
    { en: "akaza_akari", cn: "赤座灯里" },
    { en: "aki_minoriko", cn: "秋穰子" },
    { en: "aki_rosenthal", cn: "秋罗森塔尔" },
    { en: "aki_shizuha", cn: "秋静叶" },
    { en: "akigumo_(kancolle)", cn: "秋云（舰队收藏）" },
    { en: "akiyama_mizuki", cn: "秋山瑞月" },
    { en: "akiyama_yukari", cn: "秋山优花里" },
    { en: "akizuki_(kancolle)", cn: "秋月（舰队收藏）" },
    { en: "akizuki_ritsuko", cn: "秋月律子" },
    { en: "ako_(blue_archive)", cn: "亚子（蔚蓝档案）" },
    { en: "ako_(dress)_(blue_archive)", cn: "亚子（礼服）（蔚蓝档案）" },
    { en: "akuma_homura", cn: "恶魔焰" },
    { en: "albedo_(genshin_impact)", cn: "阿贝多（原神）" },
    { en: "albedo_(overlord)", cn: "阿尔贝多（OVERLORD）" },
    { en: "alear_(female)_(fire_emblem)", cn: "艾莉尔（女）（火焰纹章）" },
    { en: "alear_(fire_emblem)", cn: "艾莉尔（火焰纹章）" },
    { en: "alice_(alice_in_wonderland)", cn: "爱丽丝（爱丽丝梦游仙境）" },
    { en: "alice_margatroid_(pc-98)", cn: "爱丽丝·玛格特洛依德（PC-98）" },
    { en: "alina_gray", cn: "阿莉娜·格雷" },
    { en: "alisa_ilinichina_amiella", cn: "艾丽莎·伊莉妮齐娜·阿米耶拉" },
    { en: "alolan_vulpix", cn: "阿罗拉六尾" },
    { en: "alpaca_suri_(kemono_friends)", cn: "羊驼苏里（兽娘动物园）" },
    { en: "altaria", cn: "七夕青鸟" },
    { en: "altera_(fate)", cn: "阿尔托莉雅（命运）" },
    { en: "amagi_(azur_lane)", cn: "天城（碧蓝航线）" },
    { en: "amamiya_kokoro", cn: "天宫心" },
    { en: "amamiya_ren", cn: "雨宫莲" },
    { en: "amanekanata", cn: "天音彼方" },
    { en: "amanekanata_(1st_costume)", cn: "天音彼方（第一服装）" },
    { en: "amanogawa_kirara", cn: "天之川绮罗罗" },
    { en: "amber_(genshin_impact)", cn: "安柏（原神）" },
    { en: "ame-chan_(needy_girl_overdose)", cn: "雨酱（NEEDY GIRL OVERDOSE）" },
    { en: "amy_rose", cn: "艾米·罗斯" },
    { en: "an-94_(girls'_frontline)", cn: "AN-94（少女前线）" },
    { en: "anastasia_(fate)", cn: "阿纳斯塔西娅（命运）" },
    { en: "anastasia_(idolmaster)", cn: "阿纳斯塔西娅（偶像大师）" },
    { en: "anchovy_(girls_und_panzer)", cn: "安丘比（少女与战车）" },
    { en: "android_18", cn: "18号" },
    { en: "android_21", cn: "21号" },
    { en: "angel_(kof)", cn: "安琪儿（拳皇）" },
    { en: "angela_(project_moon)", cn: "安吉拉（Project Moon）" },
    { en: "angelina_(arknights)", cn: "安洁莉娜（明日方舟）" },
    { en: "anila_(granblue_fatnasy)", cn: "阿尼拉（碧蓝幻想）" },
    { en: "anis_(nikke)", cn: "阿妮斯（妮姬）" },
    { en: "annie_leonhart", cn: "安妮·利昂哈特" },
    { en: "anya_(spy_x_family)", cn: "阿尼亚（间谍过家家）" },
    { en: "anyoji_hime", cn: "安与城姬" },
    { en: "aoba_(kancolle)", cn: "青叶（舰队收藏）" },
    { en: "aoki_reika", cn: "青木铃花" },
    { en: "aqua_(konosuba)", cn: "阿库娅（为美好的世界献上祝福）" },
    { en: "aranara_(genshin_impact)", cn: "兰那罗（原神）" },
    { en: "araragi_karen", cn: "阿良良木火怜" },
    { en: "arashi_(kancolle)", cn: "岚（舰队收藏）" },
    { en: "arashio_(kancolle)", cn: "朝潮（舰队收藏）" },
    { en: "arch_bishop_(ragnarok_online)", cn: "大主教（仙境传说）" },
    { en: "arcueid_brunestud", cn: "爱尔奎特·布伦史塔德" },
    { en: "aris_(maid)_(blue_archive)", cn: "阿莉丝（女仆）（蔚蓝档案）" },
    { en: "arisugawa_natsuha", cn: "有栖川夏叶" },
    { en: "ark_royal_(kancolle)", cn: "皇家方舟（舰队收藏）" },
    { en: "arle_nadja", cn: "阿鲁鲁·娜迪亚" },
    { en: "arlecchino_(genshin_impact)", cn: "阿尔莱基诺（原神）" },
    { en: "arona_(blue_archive)", cn: "阿罗娜（蔚蓝档案）" },
    { en: "artoria_caster_(fate)", cn: "阿尔托莉雅·卡斯特（命运）" },
    { en: "artoria_pendragon_(alter_swimsuit_rider)_(fate)", cn: "阿尔托莉雅·潘德拉贡（泳装骑阶）（命运）" },
    { en: "artoria_pendragon_(alter_swimsuit_rider)_(second_ascension)_(fate)", cn: "阿尔托莉雅·潘德拉贡（泳装骑阶二破）（命运）" },
    { en: "artoria_pendragon_(lancer)_(fate)", cn: "阿尔托莉雅·潘德拉贡（枪阶）（命运）" },
    { en: "artoria_pendragon_(swimsuit_ruler)_(fate)", cn: "阿尔托莉雅·潘德拉贡（泳装裁定者）（命运）" },
    { en: "artoria_pendragon_(swimsuit_ruler)_(first_ascension)_(fate)", cn: "阿尔托莉雅·潘德拉贡（泳装裁定者一破）（命运）" },
    { en: "aru_(blue_archive)", cn: "阿露（蔚蓝档案）" },
    { en: "asagumo_(kancolle)", cn: "朝云（舰队收藏）" },
    { en: "asahina_mafuyu", cn: "朝日奈真冬" },
    { en: "asakura_toru", cn: "浅仓透" },
    { en: "asashimo_(kancolle)", cn: "朝霜（舰队收藏）" },
    { en: "ashigara_(kancolle)", cn: "足柄（舰队收藏）" },
    { en: "ashiya_douman_(fate)", cn: "芦屋道满（命运）" },
    { en: "assam_(girls_und_panzer)", cn: "阿萨姆（少女与战车）" },
    { en: "astolfo_(fate)", cn: "阿斯托尔福（命运）" },
    { en: "astolfo_(sailor_paladin)_(fate)", cn: "阿斯托尔福（水手圣骑士）（命运）" },
    { en: "asuna_(bunny)_(blue_archive)", cn: "亚丝娜（兔女郎）（蔚蓝档案）" },
    { en: "asuna_(sao)", cn: "亚丝娜（刀剑神域）" },
    { en: "asuna_(school_uniform)_(blue_archive)", cn: "亚丝娜（校服）（蔚蓝档案）" },
    { en: "atago_(azur_lane)", cn: "爱宕（碧蓝航线）" },
    { en: "atalanta_(fate)", cn: "阿塔兰忒（命运/冠位指定）" },
    { en: "atlanta_(kancolle)", cn: "亚特兰大（舰队Collection）" },
    { en: "atsuko_(blue_archive)", cn: "亚津子（蔚蓝档案）" },
    { en: "aventurine_(honkai:_star_rail)", cn: "阿维林（崩坏：星穹铁道）" },
    { en: "ayanami_(azur_lane)", cn: "绫波（碧蓝航线）" },
    { en: "ayanami_rei", cn: "绫波丽（新世纪福音战士）" },
    { en: "ayane_(blue_archive)", cn: "亚夜音（蔚蓝档案）" },
    { en: "azki_(hololive)", cn: "AZKi（Hololive）" },
    { en: "azura_(fire_emblem)", cn: "阿库娅（火焰之纹章）" },
    { en: "azusa_(blue_archive)", cn: "梓（蔚蓝档案）" },
    { en: "backbeard", cn: "巴库巴多（恶魔人）" },
    { en: "baiken", cn: "梅喧（罪恶装备）" },
    { en: "baltimore_(azur_lane)", cn: "巴尔的摩（碧蓝航线）" },
    { en: "baobhan_sith_(fate)", cn: "巴万·希丝（命运/冠位指定）" },
    { en: "baobhan_sith_(first_ascension)_(fate)", cn: "巴万·希丝（第一灵基）（命运/冠位指定）" },
    { en: "barbara_(genshin_impact)", cn: "芭芭拉（原神）" },
    { en: "barghest_(fate)", cn: "巴格斯特（命运/冠位指定）" },
    { en: "basil_(headspace)_(omori)", cn: "巴兹尔（思维空间）（OMORI）" },
    { en: "basil_(omori)", cn: "巴兹尔（OMORI）" },
    { en: "battleship_princess", cn: "战舰公主（舰队Collection）" },
    { en: "bayonetta", cn: "贝优妮塔（猎天使魔女）" },
    { en: "bb_(fate)", cn: "BB（命运/冠位指定）" },
    { en: "bb_(fate/extra)", cn: "BB（命运/EXTRA）" },
    { en: "beatrice_(umineko)", cn: "贝阿朵莉切（海猫鸣泣之时）" },
    { en: "beidou_(genshin_impact)", cn: "北斗（原神）" },
    { en: "belfast_(azur_lane)", cn: "贝尔法斯特（碧蓝航线）" },
    { en: "bianca_(pokemon)", cn: "白露（宝可梦）" },
    { en: "bibi_(tokoyami_towa)", cn: "比比（常闇永远）" },
    { en: "black_rock_shooter_(character)", cn: "黑岩射手（黑岩射手）" },
    { en: "black_swan_(honkai:_star_rail)", cn: "黑天鹅（崩坏：星穹铁道）" },
    { en: "blade_(honkai:_star_rail)", cn: "刃（崩坏：星穹铁道）" },
    { en: "blake_belladonna", cn: "布莱克·贝拉多纳（RWBY）" },
    { en: "blaze_(arknights)", cn: "煌（明日方舟）" },
    { en: "bloop_(gawr_gura)", cn: "布洛普（噶呜·古拉）" },
    { en: "blue_poison_(arknights)", cn: "蓝毒（明日方舟）" },
    { en: "boo_(mario)", cn: "嘘嘘鬼（马里奥）" },
    { en: "bowser", cn: "库巴（马里奥）" },
    { en: "bowsette", cn: "库巴姬（马里奥/同人创作）" },
    { en: "bremerton_(azur_lane)", cn: "布雷默顿（碧蓝航线）" },
    { en: "bremerton_(scorching-hot_training)_(azur_lane)", cn: "布雷默顿（炽热训练）（碧蓝航线）" },
    { en: "bronya_zaychik", cn: "布洛妮娅·扎伊切克（崩坏系列）" },
    { en: "bronya_zaychik_(silverwing:_n-ex)", cn: "布洛妮娅·扎伊切克（银翼：N-EX）（崩坏系列）" },
    { en: "bulbasaur", cn: "妙蛙种子（宝可梦）" },
    { en: "byleth_(female)_(fire_emblem)", cn: "贝雷丝（女）（火焰之纹章）" },
    { en: "byleth_(male)_(fire_emblem)", cn: "贝雷特（男）（火焰之纹章）" },
    { en: "c.c.", cn: "C.C.（反叛的鲁路修）" },
    { en: "caelus_(honkai:_star_rail)", cn: "凯勒斯（崩坏：星穹铁道）" },
    { en: "cagliostro_(granblue_fantasy)", cn: "卡利欧斯托罗（碧蓝幻想）" },
    { en: "camilla_(fire_emblem)", cn: "卡米拉（火焰之纹章）" },
    { en: "cammy_white", cn: "嘉米·怀特（街头霸王）" },
    { en: "captain_(kemono_friends)", cn: "园长（兽娘动物园）" },
    { en: "caren_hortensia", cn: "卡莲·奥尔黛西亚（Fate系列）" },
    { en: "celestia_ludenberg", cn: "赛蕾丝缇雅·鲁登堡（弹丸论破）" },
    { en: "ceres_fauna", cn: "赛瑞尔·芙娜（Hololive）" },
    { en: "ceres_fauna_(1st_costume)", cn: "赛瑞尔·芙娜（第一套服装）（Hololive）" },
    { en: "ch'en_(arknights)", cn: "陈（明日方舟）" },
    { en: "changli_(wuthering_waves)", cn: "长离（鸣潮）" },
    { en: "charlotte_(madoka_magica)", cn: "夏洛特（魔法少女小圆）" },
    { en: "cheshire_(azur_lane)", cn: "柴郡（碧蓝航线）" },
    { en: "cheval_grand_(umamusume)", cn: "大马（赛马娘）" },
    { en: "chibi_usa", cn: "小小兔（美少女战士）" },
    { en: "chihaya_anon", cn: "千早亚音（偶像大师）" },
    { en: "chikorita", cn: "菊草叶（宝可梦）" },
    { en: "chiori_(genshin_impact)", cn: "千织（原神）" },
    { en: "chitose_(kancolle)", cn: "千岁（舰队Collection）" },
    { en: "chiyoda_momo", cn: "千代田桃子（偶像大师）" },
    { en: "chongyue_(arknights)", cn: "重岳（明日方舟）" },
    { en: "chongyun_(genshin_impact)", cn: "重云（原神）" },
    { en: "choukai_(kancolle)", cn: "鸟海（舰队Collection）" },
    { en: "chouzetsusaikawa_tenshi-chan", cn: "超绝西川天使酱（东方Project）" },
    { en: "chrom_(fire_emblem)", cn: "克罗姆（火焰之纹章）" },
    { en: "citlali_(genshin_impact)", cn: "西特拉里（原神）" },
    { en: "clorinde_(genshin_impact)", cn: "克洛琳德（原神）" },
    { en: "clownpiece", cn: "小丑（东方Project）" },
    { en: "collei_(genshin_impact)", cn: "柯莱（原神）" },
    { en: "colorado_(kancolle)", cn: "科罗拉多（舰队Collection）" },
    { en: "commander_(girls'_frontline)", cn: "指挥官（少女前线）" },
    { en: "copano_rickey_(umamusume)", cn: "哥白尼·瑞基（赛马娘）" },
    { en: "corrin_(female)_(fire_emblem)", cn: "库洛姆（女）（火焰之纹章）" },
    { en: "corrin_(fire_emblem)", cn: "库洛姆（火焰之纹章）" },
    { en: "corrin_(male)_(fire_emblem)", cn: "库洛姆（男）（火焰之纹章）" },
    { en: "crystalfly_(genshin_impact)", cn: "晶蝶（原神）" },
    { en: "cure_beauty", cn: "美丽天使（光之美少女）" },
    { en: "cure_black", cn: "黑天使（光之美少女）" },
    { en: "cure_blossom", cn: "花天使（光之美少女）" },
    { en: "cure_marine", cn: "海洋天使（光之美少女）" },
    { en: "cure_peace", cn: "和平天使（光之美少女）" },
    { en: "cure_sky", cn: "天空天使（光之美少女）" },
    { en: "cure_sunshine", cn: "阳光天使（光之美少女）" },
    { en: "cure_white", cn: "白天使（光之美少女）" },
    { en: "curren_chan_(umamusume)", cn: "库伦酱（赛马娘）" },
    { en: "cyno_(genshin_impact)", cn: "赛诺（原神）" },
    { en: "cynthia_(pokemon)", cn: "辛俐（宝可梦）" },
    { en: "d.va_(overwatch)", cn: "D.Va（守望先锋）" },
    { en: "daidouji_tomoyo", cn: "大道寺知世（魔卡少女樱）" },
    { en: "daitaku_helios_(umamusume)", cn: "大拓太阳神（赛马娘）" },
    { en: "daiwa_scarlet_(umamusume)", cn: "大和赤骥（赛马娘）" },
    { en: "dan_heng_(honkai:_star_rail)", cn: "丹恒（崩坏：星穹铁道）" },
    { en: "dan_heng_(imbibitor_lunae)_(honkai:_star_rail)", cn: "丹恒·饮月君（崩坏：星穹铁道）" },
    { en: "dantsu_flame_(umamusume)", cn: "丹津烈焰（赛马娘）" },
    { en: "dark_magician_girl", cn: "黑魔术少女（游戏王）" },
    { en: "darkness_(konosuba)", cn: "达克妮丝（为美好的世界献上祝福）" },
    { en: "dido_(azur_lane)", cn: "狄朵（碧蓝航线）" },
    { en: "diluc_(genshin_impact)", cn: "迪卢克（原神）" },
    { en: "diona_(genshin_impact)", cn: "迪奥娜（原神）" },
    { en: "dizzy_(guilty_gear)", cn: "蒂兹（罪恶装备）" },
    { en: "dodoco_(genshin_impact)", cn: "嘟嘟可（原神）" },
    { en: "don-chan_(usada_pekora)", cn: "咚酱（兔田佩克拉）" },
    { en: "doodle_sensei_(blue_archive)", cn: "涂鸦老师（蔚蓝档案）" },
    { en: "dorothea_arnault", cn: "多萝西·阿诺尔特（火焰之纹章）" },
    { en: "dr._ratio_(honkai:_star_rail)", cn: "博士比率（崩坏：星穹铁道）" },
    { en: "dusk_(arknights)", cn: "夕（明日方舟）" },
    { en: "edelgard_von_hresvelg", cn: "艾黛尔贾特·冯·弗雷斯贝尔古（火焰之纹章）" },
    { en: "eevee", cn: "伊布（宝可梦）" },
    { en: "eila_ilmatar_juutilainen", cn: "艾拉·伊尔玛塔·尤蒂莱宁（强袭魔女）" },
    { en: "eimi_(blue_archive)", cn: "绘未（蔚蓝档案）" },
    { en: "eishin_flash_(umamusume)", cn: "荣进闪光（赛马娘）" },
    { en: "elaina_(majo_no_tabitabi)", cn: "伊蕾娜（魔女之旅）" },
    { en: "elesa_(pokemon)", cn: "艾莉萨（宝可梦）" },
    { en: "elin", cn: "艾琳（英雄联盟）" },
    { en: "elira_pendora", cn: "伊莉拉·彭朵拉（Nijisanji）" },
    { en: "elizabeth_bathory_(fate)", cn: "伊丽莎白·巴陶里（命运/冠位指定）" },
    { en: "elizabeth_bathory_(fate/extra)", cn: "伊丽莎白·巴陶里（命运/EXTRA）" },
    { en: "ellen_joe", cn: "艾伦·乔（赛马娘）" },
    { en: "elphelt_valentine", cn: "埃尔菲尔特·情人节（罪恶装备）" },
    { en: "elysia_(herrscher_of_human:_ego)_(honkai_impact)", cn: "爱莉希雅（人类·自我之律者）（崩坏3）" },
    { en: "elysia_(honkai_impact)", cn: "爱莉希雅（崩坏3）" },
    { en: "elysia_(miss_pink_elf)_(honkai_impact)", cn: "爱莉希雅（粉色妖精小姐）（崩坏3）" },
    { en: "emilia_(re:zero)", cn: "艾米莉娅（Re:从零开始的异世界生活）" },
    { en: "emperor_penguin_(kemono_friends)", cn: "皇帝企鹅（兽娘动物园）" },
    { en: "enkidu_(fate)", cn: "恩奇都（命运/冠位指定）" },
    { en: "enna_alouette", cn: "艾娜·阿鲁埃（Nijisanji）" },
    { en: "enoshima_junko", cn: "江之岛盾子（弹丸论破）" },
    { en: "enterprise_(azur_lane)", cn: "企业（碧蓝航线）" },
    { en: "eous_(zenless_zone_zero)", cn: "伊奥斯（无期迷途）" },
    { en: "ereshkigal_(fate)", cn: "艾列什基伽尔（命运/冠位指定）" },
    { en: "erika_(pokemon)", cn: "莉佳（宝可梦）" },
    { en: "eris_greyrat", cn: "艾莉丝·格雷拉特（无职转生）" },
    { en: "espeon", cn: "太阳伊布（宝可梦）" },
    { en: "estellise_sidos_heurassein", cn: "艾丝蒂尔·塞德海姆（薄暮传说）" },
    { en: "eternity_larva", cn: "永恒幼虫（东方Project）" },
    { en: "etna_(disgaea)", cn: "艾特娜（魔界战记）" },
    { en: "etorofu_(kancolle)", cn: "择捉（舰队Collection）" },
    { en: "eula_(genshin_impact)", cn: "优菈（原神）" },
    { en: "eunie_(xenoblade)", cn: "优妮（异度神剑）" },
    { en: "euryale_(fate)", cn: "尤瑞艾莉（命运/冠位指定）" },
    { en: "eve_(elsword)", cn: "伊芙（艾尔之光）" },
    { en: "ex-keine", cn: "前任红美铃（东方Project）" },
    { en: "exusiai_(arknights)", cn: "能天使（明日方舟）" },
    { en: "eyjafjalla_(arknights)", cn: "艾雅法拉（明日方舟）" },
    { en: "failure_penguin", cn: "失败企鹅（偶像大师）" },
    { en: "fairy_(kancolle)", cn: "妖精（舰队Collection）" },
    { en: "falin_touden", cn: "法琳·托登（迷宫饭）" },
    { en: "falin_touden_(tallman)", cn: "法琳·托登（长人形态）（迷宫饭）" },
    { en: "faruzan_(genshin_impact)", cn: "珐露珊（原神）" },
    { en: "faust_(project_moon)", cn: "浮士德（月光计划）" },
    { en: "feixiao_(honkai:_star_rail)", cn: "飞霄 (崩坏：星穹铁道)" },
    { en: "fennec_(kemono_friends)", cn: "耳廓狐（兽娘动物园）" },
    { en: "ferry_(granblue_fantasy)", cn: "菲莉（碧蓝幻想）" },
    { en: "finana_ryugu", cn: "龙宫菲娜娜" },
    { en: "fine_motion_(umamusume)", cn: "微步（赛马娘）" },
    { en: "firefly_(honkai:_star_rail)", cn: "萤火虫（崩坏：星穹铁道）" },
    { en: "fischl_(genshin_impact)", cn: "菲谢尔（原神）" },
    { en: "fletcher_(kancolle)", cn: "弗莱彻（舰队Collection）" },
    { en: "florence_nightingale_(fate)", cn: "南丁格尔（命运系列）" },
    { en: "florence_nightingale_(trick_or_treatment)_(fate)", cn: "南丁格尔（Trick or Treatment）（命运系列）" },
    { en: "floyd_leech", cn: "弗洛伊德·里奇" },
    { en: "formidable_(azur_lane)", cn: "可畏（碧蓝航线）" },
    { en: "fou_(fate)", cn: "芙芙（命运系列）" },
    { en: "francesca_lucchini", cn: "弗朗西斯卡·卢基尼" },
    { en: "frankenstein's_monster_(fate)", cn: "弗兰肯斯坦的怪物（命运系列）" },
    { en: "fu_hua", cn: "符华" },
    { en: "fu_hua_(herrscher_of_sentience)", cn: "符华（识之律者）" },
    { en: "fu_xuan_(honkai:_star_rail)", cn: "符玄（崩坏：星穹铁道）" },
    { en: "fubuki_(blue_archive)", cn: "吹雪（蔚蓝档案）" },
    { en: "fudo_yusei", cn: "不动游星" },
    { en: "fuji_kiseki_(umamusume)", cn: "富士奇迹（赛马娘）" },
    { en: "fujibayashi_kyou", cn: "藤林杏" },
    { en: "fujishima_megumi", cn: "藤岛惠" },
    { en: "fujita_kotone", cn: "藤田琴音" },
    { en: "fukumaru_koito", cn: "福丸小糸" },
    { en: "fukuzawa_yumi", cn: "福泽祐美" },
    { en: "fumizuki_(kancolle)", cn: "文月（舰队Collection）" },
    { en: "furina_(genshin_impact)", cn: "芙宁娜（原神）" },
    { en: "furude_rika", cn: "古手梨花" },
    { en: "furukawa_nagisa", cn: "古河渚" },
    { en: "furutaka_(kancolle)", cn: "古鹰（舰队Collection）" },
    { en: "fusou_(kancolle)", cn: "扶桑（舰队Collection）" },
    { en: "futaba_anzu", cn: "双叶杏" },
    { en: "futami_mami", cn: "双海真美" },
    { en: "futatsuiwa_mamizou", cn: "二岩猯藏" },
    { en: "fuuka_(blue_archive)", cn: "风香（蔚蓝档案）" },
    { en: "fuwawa_abyssgard", cn: "芙瓦瓦·深渊守望" },
    { en: "fuwawa_abyssgard_(1st_costume)", cn: "芙瓦瓦·深渊守望（第一服装）" },
    { en: "g11_(girls'_frontline)", cn: "G11（少女前线）" },
    { en: "gambier_bay_(kancolle)", cn: "甘比尔湾（舰队Collection）" },
    { en: "gangut_(kancolle)", cn: "甘古特（舰队Collection）" },
    { en: "ganyu_(genshin_impact)", cn: "甘雨（原神）" },
    { en: "gawr_gura", cn: "噶呜·古拉" },
    { en: "gawr_gura_(casual)", cn: "噶呜·古拉（休闲装）" },
    { en: "gengar", cn: "耿鬼" },
    { en: "gentildonna_(umamusume)", cn: "真机伶（赛马娘）" },
    { en: "gertrud_barkhorn", cn: "格特鲁德·巴克霍恩" },
    { en: "gold_ship_(umamusume)", cn: "黄金船（赛马娘）" },
    { en: "gotland_(kancolle)", cn: "哥特兰（舰队Collection）" },
    { en: "grace_howard", cn: "格蕾丝·霍华德" },
    { en: "graf_zeppelin_(kancolle)", cn: "格拉夫·齐柏林（舰队Collection）" },
    { en: "gran_(granblue_fantasy)", cn: "格兰（碧蓝幻想）" },
    { en: "grass_wonder_(umamusume)", cn: "草上飞（赛马娘）" },
    { en: "green_(pokemon)", cn: "小绿（宝可梦）" },
    { en: "grookey", cn: "敲音猴" },
    { en: "grusha_(pokemon)", cn: "格鲁沙（宝可梦）" },
    { en: "gumi", cn: "GUMI" },
    { en: "gwen_(league_of_legends)", cn: "格温（英雄联盟）" },
    { en: "gwen_stacy", cn: "格温·史黛西" },
    { en: "hachikuji_mayoi", cn: "八九寺真宵" },
    { en: "hagikaze_(kancolle)", cn: "萩风（舰队Collection）" },
    { en: "haguro_(kancolle)", cn: "羽黑（舰队Collection）" },
    { en: "hakos_baelz", cn: "哈克丝·贝琉" },
    { en: "hakos_baelz_(1st_costume)", cn: "哈克丝·贝琉（第一服装）" },
    { en: "hakui_koyori", cn: "白井小夜璃" },
    { en: "hakui_koyori_(1st_costume)", cn: "白井小夜璃（第一服装）" },
    { en: "hanako_(blue_archive)", cn: "花子（蔚蓝档案）" },
    { en: "hanako_(swimsuit)_(blue_archive)", cn: "花子（泳装）（蔚蓝档案）" },
    { en: "hanami_saki", cn: "花见酒" },
    { en: "hanami_ume", cn: "花见梅" },
    { en: "hanamura_yousuke", cn: "花村阳介" },
    { en: "hanekawa_tsubasa", cn: "羽川翼" },
    { en: "haniyasushin_keiki", cn: "埴安神袿姬" },
    { en: "hanyuu", cn: "羽入" },
    { en: "haramura_nodoka", cn: "原村和" },
    { en: "haru_urara_(umamusume)", cn: "春丽（赛马娘）" },
    { en: "haruka_(blue_archive)", cn: "遥（蔚蓝档案）" },
    { en: "harukawa_maki", cn: "春川麻纪" },
    { en: "haruna_(blue_archive)", cn: "晴奈（蔚蓝档案）" },
    { en: "haruna_kai_ni_(kancolle)", cn: "榛名改二（舰队Collection）" },
    { en: "haruno_sakura", cn: "春野樱" },
    { en: "harusame_(kancolle)", cn: "春雨（舰队Collection）" },
    { en: "hasumi_(blue_archive)", cn: "莲见（蔚蓝档案）" },
    { en: "hasumi_(track)_(blue_archive)", cn: "莲见（田径服）（蔚蓝档案）" },
    { en: "hatoba_tsugu", cn: "鳩羽津" },
    { en: "hatsukaze_(kancolle)", cn: "初风（舰队Collection）" },
    { en: "hatsune_miku", cn: "初音未来" },
    { en: "hatsune_miku_(append)", cn: "初音未来（Append）" },
    { en: "hatsushimo_(kancolle)", cn: "初霜（舰队Collection）" },
    { en: "hatsutori_hajime", cn: "初土干基" },
    { en: "hatsuzuki_(kancolle)", cn: "初月（舰队Collection）" },
    { en: "hayakawa_aki", cn: "早川秋" },
    { en: "hayami_kanade", cn: "早美加菜" },
    { en: "hayasaka_ai", cn: "早坂爱" },
    { en: "hayashimo_(kancolle)", cn: "早霜（舰队Collection）" },
    { en: "hayasui_(kancolle)", cn: "早瑞（舰队Collection）" },
    { en: "heanna_sumire", cn: "平南菫" },
    { en: "hecatia_lapislazuli", cn: "赫卡提亚·拉碧斯拉祖利" },
    { en: "helena_blavatsky_(fate)", cn: "海伦娜·布拉瓦茨基（命运系列）" },
    { en: "hello_kitty_(character)", cn: "凯蒂猫（角色）" },
    { en: "herta_(honkai:_star_rail)", cn: "黑塔（崩坏：星穹铁道）" },
    { en: "hestia_(danmachi)", cn: "赫斯缇雅（在地下城寻求邂逅是否搞错了什么）" },
    { en: "hibiki_(blue_archive)", cn: "响（蔚蓝档案）" },
    { en: "hibiki_(cheer_squad)_(blue_archive)", cn: "响（啦啦队）（蔚蓝档案）" },
    { en: "hibiki_(kancolle)", cn: "响（舰队Collection）" },
    { en: "hiei_(kancolle)", cn: "比叡（舰队Collection）" },
    { en: "hifumi_(blue_archive)", cn: "日富美（蔚蓝档案）" },
    { en: "higashiyama_kobeni", cn: "东山小红" },
    { en: "high_priest_(ragnarok_online)", cn: "大祭司（仙境传说）" },
    { en: "higuchi_kaede", cn: "樋口枫" },
    { en: "higuchi_madoka", cn: "樋口圆香" },
    { en: "hiiragi_kagami", cn: "柊镜" },
    { en: "hiiragi_tsukasa", cn: "柊司" },
    { en: "hikari_(blue_archive)", cn: "光（蔚蓝档案）" },
    { en: "hikawa_hina", cn: "川日菜" },
    { en: "hikawa_sayo", cn: "川沙耶" },
    { en: "hilda_(pokemon)", cn: "希罗娜（宝可梦）" },
    { en: "hilda_valentine_goneril", cn: "希尔达·瓦伦丁·格尼瑞尔" },
    { en: "hilichurl_(genshin_impact)", cn: "丘丘人（原神）" },
    { en: "himari_(blue_archive)", cn: "日鞠（蔚蓝档案）" },
    { en: "himejima_akeno", cn: "姬岛朱乃" },
    { en: "himeko_(honkai:_star_rail)", cn: "姬子（崩坏：星穹铁道）" },
    { en: "himemori_luna", cn: "姬森露娜" },
    { en: "himmel_(sousou_no_frieren)", cn: "希梅尔（葬送的芙莉莲）" },
    { en: "hina_(blue_archive)", cn: "日奈（蔚蓝档案）" },
    { en: "hina_(dress)_(blue_archive)", cn: "日奈（礼服）（蔚蓝档案）" },
    { en: "hina_(swimsuit)_(blue_archive)", cn: "日奈（泳装）（蔚蓝档案）" },
    { en: "hinaichigo", cn: "雏莓" },
    { en: "hino_akane_(smile_precure!)", cn: "日野茜（微笑光之美少女！）" },
    { en: "hino_rei", cn: "火野丽" },
    { en: "hinoshita_kaho", cn: "日野下佳穗" },
    { en: "hiro_(darling_in_the_franxx)", cn: "广（DARLING in the FRANXX）" },
    { en: "hiryuu_(kancolle)", cn: "飞龙（舰队Collection）" },
    { en: "hisakawa_hayate", cn: "久川飒" },
    { en: "hisakawa_nagi", cn: "久川凪" },
    { en: "hishi_miracle_(umamusume)", cn: "菱奇迹（赛马娘）" },
    { en: "hishikawa_rikka", cn: "菱川六花" },
    { en: "hiyori_(blue_archive)", cn: "日和（蔚蓝档案）" },
    { en: "hk416_(girls'_frontline)", cn: "HK416（少女前线）" },
    { en: "ho'olheyak_(arknights)", cn: "赫尔海雅（明日方舟）" },
    { en: "hojo_karen", cn: "北条迦莲" },
    { en: "hokko_tarumae_(umamusume)", cn: "北港御前（赛马娘）" },
    { en: "holo", cn: "赫萝" },
    { en: "homu_(honkai_impact)", cn: "霍姆（崩坏3）" },
    { en: "honda_mio", cn: "本田未央" },
    { en: "honebami_toushirou", cn: "骨喰藤四郎" },
    { en: "hong_lu_(project_moon)", cn: "红鹿（Project Moon）" },
    { en: "honma_meiko", cn: "本间芽衣子" },
    { en: "honolulu_(azur_lane)", cn: "檀香山（碧蓝航线）" },
    { en: "horikawa_raiko", cn: "堀川雷鼓" },
    { en: "hornet_(kancolle)", cn: "大黄蜂（舰队Collection）" },
    { en: "hoshi_syoko", cn: "星川翔子" },
    { en: "hoshiguma_(arknights)", cn: "星熊（明日方舟）" },
    { en: "hoshii_miki", cn: "星井美希" },
    { en: "hoshikawa_sara", cn: "星川纱良" },
    { en: "hoshimachi_suisei_(1st_costume)", cn: "星街彗星（第一服装）" },
    { en: "hoshimachi_suisei_(school_uniform)", cn: "星街彗星（校服）" },
    { en: "hoshimi_miyabi", cn: "星见雅" },
    { en: "hoshimiya_ichigo", cn: "星宫草莓" },
    { en: "hoshino_(swimsuit)_(blue_archive)", cn: "星野（泳装）（蔚蓝档案）" },
    { en: "hoshino_ai", cn: "星野爱" },
    { en: "hoshino_fumina", cn: "星野文" },
    { en: "hoshino_ruby", cn: "星野露比" },
    { en: "hoto_cocoa", cn: "保登心爱" },
    { en: "houjou_hibiki", cn: "北条比奈" },
    { en: "houjou_satoko", cn: "北条沙都子" },
    { en: "houjou_tokiyuki_(nige_jouzu_no_wakagimi)", cn: "北条时行（擅逃的少主）" },
    { en: "hourai_doll", cn: "蓬莱人形" },
    { en: "houshou_marine", cn: "宝钟玛琳" },
    { en: "houshou_marine_(1st_costume)", cn: "宝钟玛琳（第一服装）" },
    { en: "houshou_marine_(summer)", cn: "宝钟玛琳（夏季）" },
    { en: "hsien-ko", cn: "茜茜" },
    { en: "hu_tao_(genshin_impact)", cn: "胡桃（原神）" },
    { en: "hyakumantenbara_salome", cn: "百万玫瑰" },
    { en: "i-168_(kancolle)", cn: "伊-168（舰队Collection）" },
    { en: "i-19_(kancolle)", cn: "伊-19（舰队Collection）" },
    { en: "i-26_(kancolle)", cn: "伊-26（舰队Collection）" },
    { en: "i-58_(kancolle)", cn: "伊-58（舰队Collection）" },
    { en: "i-8_(kancolle)", cn: "I-8（舰队Collection）" },
    { en: "ia_(vocaloid)", cn: "IA（Vocaloid）" },
    { en: "ibuki_(blue_archive)", cn: "伊吹（蔚蓝档案）" },
    { en: "ichihara_nina", cn: "市原仁奈" },
    { en: "ichika_(blue_archive)", cn: "一花（蔚蓝档案）" },
    { en: "ichikawa_hinana", cn: "市川雛菜" },
    { en: "ichinose_shiki", cn: "一之濑诗纪" },
    { en: "ifrit_(arknights)", cn: "伊芙利特（明日方舟）" },
    { en: "igarashi_futaba", cn: "五十岚双叶" },
    { en: "iizunamaru_megumu", cn: "饭纲丸芽麦" },
    { en: "ikamusume", cn: "乌贼娘" },
    { en: "illustrious_(azur_lane)", cn: "光辉（碧蓝航线）" },
    { en: "ilulu_(maidragon)", cn: "伊露露（小林家的龙女仆）" },
    { en: "inazuma_(kancolle)", cn: "电（舰队Collection）" },
    { en: "ingrid_brandl_galatea", cn: "英格丽德·布兰德·加拉蒂亚" },
    { en: "intrepid_(kancolle)", cn: "无畏（舰队Collection）" },
    { en: "inubashiri_momiji", cn: "犬走椛" },
    { en: "inugami_korone", cn: "戌神沁音" },
    { en: "inugami_korone_(1st_costume)", cn: "戌神沁音（第一套服装）" },
    { en: "inui_toko", cn: "乾塔子" },
    { en: "inuyama_aoi", cn: "犬山葵" },
    { en: "iono_(pokemon)", cn: "小菘（宝可梦）" },
    { en: "iori_(blue_archive)", cn: "伊织（蔚蓝档案）" },
    { en: "iori_(swimsuit)_(blue_archive)", cn: "伊织（泳装）（蔚蓝档案）" },
    { en: "iowa_(kancolle)", cn: "爱荷华（舰队Collection）" },
    { en: "irene_(arknights)", cn: "艾丽妮（明日方舟）" },
    { en: "irida_(pokemon)", cn: "吉尔（宝可梦）" },
    { en: "irisviel_von_einzbern", cn: "爱丽丝菲尔·冯·爱因兹贝伦" },
    { en: "iroha_(blue_archive)", cn: "伊吕波（蔚蓝档案）" },
    { en: "iroha_(samurai_spirits)", cn: "伊吕波（侍魂）" },
    { en: "irys_(hololive)", cn: "IRyS（Hololive）" },
    { en: "isekaijoucho", cn: "异世界情绪" },
    { en: "iseri_nina", cn: "伊濑莉仁菜" },
    { en: "ishtar_(fate)", cn: "伊什塔尔（Fate）" },
    { en: "island_fox_(kemono_friends)", cn: "岛狐（兽娘动物园）" },
    { en: "isoi_reiji", cn: "磯井礼次" },
    { en: "isokaze_(kancolle)", cn: "矶风（舰队Collection）" },
    { en: "isshiki_iroha", cn: "一色彩羽" },
    { en: "isuzu_(kancolle)", cn: "五十铃（舰队Collection）" },
    { en: "isuzu_hana", cn: "五十铃花" },
    { en: "itsumi_erika", cn: "伊津美惠理香" },
    { en: "izayoi_aki", cn: "十六夜秋" },
    { en: "izumi-no-kami_kanesada", cn: "和泉守兼定" },
    { en: "izumi_mei", cn: "和泉明" },
    { en: "izumi_sagiri", cn: "和泉纱雾" },
    { en: "izuna_(blue_archive)", cn: "伊月（蔚蓝档案）" },
    { en: "izuna_(swimsuit)_(blue_archive)", cn: "伊月（泳装）（蔚蓝档案）" },
    { en: "jack-o'_valentine", cn: "杰克·O（情人节）" },
    { en: "jack_the_ripper_(fate/apocrypha)", cn: "开膛手杰克（Fate/Apocrypha）" },
    { en: "jakuzure_nonon", cn: "蛇崩乃音" },
    { en: "jane_doe_(zenless_zone_zero)", cn: "简·多伊（绝区零）" },
    { en: "japanese_crested_ibis_(kemono_friends)", cn: "日本冠朱鹮（兽娘动物园）" },
    { en: "javelin_(azur_lane)", cn: "标枪（碧蓝航线）" },
    { en: "jean_(genshin_impact)", cn: "琴（原神）" },
    { en: "jeanne_d'arc_(ruler)_(fate)", cn: "贞德（裁定者）（Fate）" },
    { en: "jeanne_d'arc_(swimsuit_archer)_(fate)", cn: "贞德（泳装弓兵）（Fate）" },
    { en: "jeanne_d'arc_alter_(fate)", cn: "贞德 Alter（Fate）" },
    { en: "jeanne_d'arc_alter_(swimsuit_berserker)_(fate)", cn: "贞德 Alter（泳装狂战士）（Fate）" },
    { en: "jeanne_d'arc_alter_(ver._shinjuku_1999)_(fate)", cn: "贞德 Alter（新宿1999版）（Fate）" },
    { en: "jeanne_d'arc_alter_santa_lily_(fate)", cn: "贞德 Alter 圣诞 Lily（Fate）" },
    { en: "jervis_(kancolle)", cn: "杰维斯（舰队Collection）" },
    { en: "jigglypuff", cn: "胖丁" },
    { en: "jill_valentine", cn: "吉尔·瓦伦丁" },
    { en: "jingei_(kancolle)", cn: "迅鲸（舰队Collection）" },
    { en: "jingliu_(honkai:_star_rail)", cn: "镜流（崩坏：星穹铁道）" },
    { en: "jintsuu_(kancolle)", cn: "神通（舰队Collection）" },
    { en: "jintsuu_kai_ni_(kancolle)", cn: "神通改二（舰队Collection）" },
    { en: "johnston_(kancolle)", cn: "约翰斯顿（舰队Collection）" },
    { en: "jolteon", cn: "雷精灵" },
    { en: "jougasaki_mika", cn: "城ヶ崎美嘉" },
    { en: "jougasaki_rika", cn: "城ヶ崎莉香" },
    { en: "joutouguu_mayumi", cn: "浄土宫真由美" },
    { en: "jumpy_dumpty", cn: "弹跳炸弹" },
    { en: "jun'you_(kancolle)", cn: "隼鹰（舰队Collection）" },
    { en: "jungle_pocket_(umamusume)", cn: "丛林口袋（赛马娘）" },
    { en: "junko_(touhou)", cn: "纯狐（东方Project）" },
    { en: "justice_task_force_member_(blue_archive)", cn: "正义实施部成员（蔚蓝档案）" },
    { en: "kachimachi_kosuzu", cn: "价町小铃" },
    { en: "kaedehara_kazuha", cn: "枫原万叶（原神）" },
    { en: "kaenbyou_rin_(cat)", cn: "火焰猫燐（猫形态）" },
    { en: "kaeya_(genshin_impact)", cn: "凯亚（原神）" },
    { en: "kaf_(kamitsubaki_studio)", cn: "Kaf（神椿Studio）" },
    { en: "kafka_(honkai:_star_rail)", cn: "卡芙卡（崩坏：星穹铁道）" },
    { en: "kaga_(azur_lane)", cn: "加贺（碧蓝航线）" },
    { en: "kagamihara_nadeshiko", cn: "各务原抚子" },
    { en: "kagari_atsuko", cn: "篝敦子" },
    { en: "kagerou_(kancolle)", cn: "阳炎（舰队Collection）" },
    { en: "kagura_(gintama)", cn: "神乐（银魂）" },
    { en: "kaguya_luna", cn: "辉夜月" },
    { en: "kako_(kancolle)", cn: "加古（舰队Collection）" },
    { en: "kal'tsit_(arknights)", cn: "凯尔希（明日方舟）" },
    { en: "kama_(fate)", cn: "迦摩（Fate）" },
    { en: "kamado_nezuko", cn: "灶门祢豆子" },
    { en: "kamikaze_(kancolle)", cn: "神风（舰队Collection）" },
    { en: "kamikita_komari", cn: "上北小鞠" },
    { en: "kamio_misuzu", cn: "神尾观铃" },
    { en: "kamisato_ayaka", cn: "神里绫华（原神）" },
    { en: "kamisato_ayato", cn: "神里绫人（原神）" },
    { en: "kamishiro_rui", cn: "神城琉衣" },
    { en: "kamoi_(kancolle)", cn: "加茂衣（舰队Collection）" },
    { en: "kamui_gakupo", cn: "神威乐步" },
    { en: "kamukura_izuru", cn: "神座出流" },
    { en: "kaname_raana", cn: "要拉娜" },
    { en: "kanna_(blue_archive)", cn: "佳奈（蔚蓝档案）" },
    { en: "kanna_(swimsuit)_(blue_archive)", cn: "佳奈（泳装）（蔚蓝档案）" },
    { en: "kanna_kamui", cn: "神奈神威" },
    { en: "kanroji_mitsuri", cn: "甘露寺蜜璃" },
    { en: "kanzaki_ranko", cn: "神崎兰子" },
    { en: "karyl_(princess_connect!)", cn: "凯露（公主连结！）" },
    { en: "kasaki_nozomi", cn: "笠希希美" },
    { en: "kasane_teto", cn: "重音Teto" },
    { en: "kasane_teto_(sv)", cn: "重音Teto（SV）" },
    { en: "kashino_(azur_lane)", cn: "柏野（碧蓝航线）" },
    { en: "kashiwazaki_sena", cn: "柏崎星奈" },
    { en: "kashuu_kiyomitsu", cn: "加州清光" },
    { en: "kasumi_(blue_archive)", cn: "香澄（蔚蓝档案）" },
    { en: "kasumi_(kancolle)", cn: "霞（舰队Collection）" },
    { en: "kasumi_kai_ni_(kancolle)", cn: "霞改二（舰队Collection）" },
    { en: "katori_(kancolle)", cn: "香取（舰队Collection）" },
    { en: "katou_asuka", cn: "加藤朝香" },
    { en: "katou_megumi", cn: "加藤惠" },
    { en: "katsuragi_(kancolle)", cn: "葛城（舰队Collection）" },
    { en: "katsuragi_ace_(umamusume)", cn: "桂冠王牌（赛马娘）" },
    { en: "katsushika_hokusai_(fate)", cn: "葛饰北斋（Fate）" },
    { en: "katyusha_(girls_und_panzer)", cn: "喀秋莎（少女与战车）" },
    { en: "kaveh_(genshin_impact)", cn: "卡维（原神）" },
    { en: "kawakaze_(kancolle)", cn: "川风（舰队Collection）" },
    { en: "kawaragi_momoka", cn: "川雾桃花" },
    { en: "kay_(girls_und_panzer)", cn: "凯伊（少女与战车）" },
    { en: "kayoko_(blue_archive)", cn: "佳世子（蔚蓝档案）" },
    { en: "kayoko_(dress)_(blue_archive)", cn: "佳世子（礼服）（蔚蓝档案）" },
    { en: "kazagumo_(kancolle)", cn: "风云（舰队Collection）" },
    { en: "kazama_iroha", cn: "风间色叶" },
    { en: "kazama_iroha_(1st_costume)", cn: "风间色叶（第一套服装）" },
    { en: "kazanari_tsubasa", cn: "风鸣翼" },
    { en: "kazano_hiori", cn: "风野火织" },
    { en: "kazusa_(band)_(blue_archive)", cn: "加藤（乐队）（蔚蓝档案）" },
    { en: "kazusa_(blue_archive)", cn: "加藤（蔚蓝档案）" },
    { en: "kemomimi-chan_(naga_u)", cn: "兽耳娘（长门）" },
    { en: "keqing_(genshin_impact)", cn: "刻晴（原神）" },
    { en: "kero_(cardcaptor_sakura)", cn: "可鲁贝洛斯（魔卡少女樱）" },
    { en: "kiana_kaslana", cn: "琪亚娜·卡斯兰娜" },
    { en: "kijin_seija", cn: "鬼人正邪" },
    { en: "kikuchi_makoto", cn: "菊地诚" },
    { en: "kikyou_(blue_archive)", cn: "桔梗（蔚蓝档案）" },
    { en: "king_halo_(umamusume)", cn: "王者光环（赛马娘）" },
    { en: "king_hassan_(fate)", cn: "山之翁（Fate）" },
    { en: "kino_(kino_no_tabi)", cn: "奇诺（奇诺之旅）" },
    { en: "kino_makoto", cn: "鬼乃麦" },
    { en: "kinomoto_sakura_(magic_dream_costume)", cn: "木之本樱（魔法梦装）" },
    { en: "kinugasa_(kancolle)", cn: "衣笠（舰队Collection）" },
    { en: "kiran_(fire_emblem)", cn: "基连（火焰纹章）" },
    { en: "kirara_(blue_archive)", cn: "绮拉拉（蔚蓝档案）" },
    { en: "kirara_(genshin_impact)", cn: "绮良良（原神）" },
    { en: "kirigiri_kyoko", cn: "雾切响子" },
    { en: "kirijou_mitsuru", cn: "雾岛美津" },
    { en: "kirima_syaro", cn: "桐间纱路" },
    { en: "kirino_ranmaru", cn: "桐野兰丸" },
    { en: "kirishima_(kancolle)", cn: "雾岛（舰队Collection）" },
    { en: "kirito", cn: "桐人" },
    { en: "kiriya_aoi", cn: "桐谷葵" },
    { en: "kiryu_coco", cn: "桐生可可" },
    { en: "kiryu_coco_(1st_costume)", cn: "桐生可可（第一套服装）" },
    { en: "kisaragi_(kancolle)", cn: "如月（舰队Collection）" },
    { en: "kisaragi_chihaya", cn: "如月千早" },
    { en: "kisaragi_shintarou", cn: "如月伸太郎" },
    { en: "kishin_sagume", cn: "鬼神萨迦" },
    { en: "kiso_(kancolle)", cn: "木曾（舰队Collection）" },
    { en: "kiss-shot_acerola-orion_heart-under-blade", cn: "忍野忍（化物语）" },
    { en: "kitasan_black_(umamusume)", cn: "北黑（赛马娘）" },
    { en: "kiyohime_(fate)", cn: "清姬（Fate）" },
    { en: "kiyoshimo_(kancolle)", cn: "清霜（舰队Collection）" },
    { en: "kizuna_ai", cn: "绊爱" },
    { en: "kizuna_akari", cn: "绊亚香里" },
    { "en": "kochou_shinobu", "cn": "胡蝶忍" },
    { "en": "kohaku_(tsukihime)", "cn": "琥珀（月姬）" },
    { "en": "koharu_(blue_archive)", "cn": "小春（蔚蓝档案）" },
    { "en": "koharu_(swimsuit)_(blue_archive)", "cn": "小春（泳装）（蔚蓝档案）" },
    { "en": "kokkoro_(princess_connect!)", "cn": "可可萝（公主连结！）" },
    { "en": "kokona_(blue_archive)", "cn": "心奈（蔚蓝档案）" },
    { "en": "komaeda_nagito", "cn": "狛枝凪斗" },
    { "en": "komano_aunn", "cn": "古明地阿吽" },
    { "en": "komiya_kaho", "cn": "小宮果穂" },
    { "en": "kongou_kai_ni_(kancolle)", "cn": "金刚改二（舰队Collection）" },
    { "en": "konjiki_no_yami", "cn": "金色暗影" },
    { "en": "konno_junko", "cn": "绀野纯子" },
    { "en": "konoe_kanata", "cn": "近卫奏多" },
    { "en": "kos-mos", "cn": "KOS-MOS" },
    { "en": "kosaka_honoka", "cn": "高坂穗乃果" },
    { "en": "koseki_bijou", "cn": "宝石之光" },
    { "en": "koshimizu_sachiko", "cn": "小清水佐知子" },
    { "en": "kotonoha_akane", "cn": "琴叶茜" },
    { "en": "kotonoha_aoi", "cn": "琴叶葵" },
    { "en": "kousaka_tamaki", "cn": "高坂环" },
    { "en": "kouzuki_kallen", "cn": "红月卡莲" },
    { "en": "koyanskaya_(fate)", "cn": "高扬斯卡娅（Fate）" },
    { "en": "koyuki_(blue_archive)", "cn": "小雪（蔚蓝档案）" },
    { "en": "kozakura_marry", "cn": "小桜マリー" },
    { "en": "kris_(pokemon)", "cn": "克里斯（宝可梦）" },
    { "en": "krista_lenz", "cn": "克里斯塔·连兹" },
    { "en": "kudamaki_tsukasa", "cn": "管卷司" },
    { "en": "kujikawa_rise", "cn": "久慈川理世" },
    { "en": "kujou_karen", "cn": "九条可怜" },
    { "en": "kujou_sara", "cn": "九条裟罗" },
    { "en": "kuki_shinobu", "cn": "久岐忍" },
    { "en": "kula_diamond", "cn": "库拉·戴雅门度" },
    { "en": "kuma_(kancolle)", "cn": "熊（舰队Collection）" },
    { "en": "kumano_(kancolle)", "cn": "熊野（舰队Collection）" },
    { "en": "kureiji_ollie", "cn": "古莱吉·奥莉" },
    { "en": "kurokoma_saki", "cn": "黑驹咲" },
    { "en": "kurosawa_ruby", "cn": "黑泽露比" },
    { "en": "kusanagi_nene", "cn": "草薙宁宁" },
    { "en": "kuzuha_(nijisanji)", "cn": "葛葉（にじさんじ）" },
    { "en": "kyoka_(princess_connect!)", "cn": "镜华（公主连结！）" },
    { "en": "kyonko", "cn": "京子" },
    { "en": "la+_darknesss", "cn": "拉普拉斯·达克妮丝" },
    { "en": "la+_darknesss_(1st_costume)", "cn": "拉普拉斯·达克妮丝（第一服装）" },
    { "en": "la_pluma_(arknights)", "cn": "拉普拉谟（明日方舟）" },
    { "en": "laffey_(azur_lane)", "cn": "拉菲（碧蓝航线）" },
    { "en": "lappland_(arknights)", "cn": "拉普兰德（明日方舟）" },
    { "en": "last_order_(toaru_majutsu_no_index)", "cn": "最后之作（魔法禁书目录）" },
    { "en": "latias", "cn": "拉帝亚斯" },
    { "en": "le_malin_(azur_lane)", "cn": "勒马尔（碧蓝航线）" },
    { "en": "leafa_(sao)", "cn": "莉法（刀剑神域）" },
    { "en": "leafeon", "cn": "叶伊布" },
    { "en": "len_(tsukihime)", "cn": "莲（月姬）" },
    { "en": "leona_heidern", "cn": "莉安娜·哈迪兰" },
    { "en": "letty_whiterock", "cn": "蕾蒂·怀特洛克" },
    { "en": "libeccio_(kancolle)", "cn": "西南风（舰队Collection）" },
    { "en": "lilith_(darkstalkers)", "cn": "莉莉丝（恶魔战士）" },
    { "en": "lily_white", "cn": "莉莉·怀特" },
    { "en": "ling_(arknights)", "cn": "令（明日方舟）" },
    { "en": "lisa_(genshin_impact)", "cn": "丽莎（原神）" },
    { "en": "little_red_riding_hood_(grimm)", "cn": "小红帽（格林童话）" },
    { "en": "litwick", "cn": "烛光灵" },
    { "en": "lize_helesta", "cn": "莉泽·赫露斯塔" },
    { "en": "louise_francoise_le_blanc_de_la_valliere", "cn": "露易丝·法兰西斯·露·布朗·德·拉·瓦利埃尔" },
    { "en": "lovely_labrynth_of_the_silver_castle", "cn": "银城的可爱迷宫" },
    { "en": "luciana_de_montefio", "cn": "露西亚娜·德·蒙特菲奥" },
    { "en": "lucifer_(helltaker)", "cn": "路西法（地狱把妹王）" },
    { "en": "lucina_(fire_emblem)", "cn": "露琪娜（火焰纹章）" },
    { "en": "lucoa_(maidragon)", "cn": "露科亚（小林家的龙女仆）" },
    { "en": "lucy_(cyberpunk)", "cn": "露西（赛博朋克）" },
    { "en": "luigi", "cn": "路易吉" },
    { "en": "lum", "cn": "拉姆" },
    { "en": "luma_(mario)", "cn": "小星星（马里奥）" },
    { "en": "lumine_(genshin_impact)", "cn": "荧（原神）" },
    { "en": "luo_xiaohei", "cn": "罗小黑" },
    { "en": "lux_(league_of_legends)", "cn": "拉克丝（英雄联盟）" },
    { "en": "lyn_(fire_emblem)", "cn": "琳（火焰纹章）" },
    { "en": "lynette_bishop", "cn": "琳内特·毕晓普" },
    { "en": "lyney_(genshin_impact)", "cn": "莱尼（原神）" },
    { "en": "lyra_(pokemon)", "cn": "琴音（宝可梦）" },
    { "en": "lyria_(granblue_fantasy)", "cn": "莉娅（碧蓝幻想）" },
    { "en": "lyrica_prismriver", "cn": "普莉兹姆利巴·莱利卡" },
    { "en": "lysithea_von_ordelia", "cn": "莉丝缇亚·冯·奥狄利亚" },
    { "en": "m16a1_(girls'_frontline)", "cn": "M16A1（少女前线）" },
    { "en": "m200_(girls'_frontline)", "cn": "M200（少女前线）" },
    { "en": "m4_sopmod_ii_(girls'_frontline)", "cn": "M4 SOPMOD II（少女前线）" },
    { "en": "m4a1_(girls'_frontline)", "cn": "M4A1（少女前线）" },
    { "en": "maebara_keiichi", "cn": "前原圭一" },
    { "en": "magical_mirai_miku", "cn": "魔法未来初音未来" },
    { "en": "magical_ruby", "cn": "红宝石魔法杖" },
    { "en": "magnemite", "cn": "小磁怪" },
    { "en": "maikaze_(kancolle)", "cn": "舞风（舰队Collection）" },
    { "en": "maizono_sayaka", "cn": "舞园沙耶香" },
    { "en": "maka_albarn", "cn": "玛卡·阿尔巴恩" },
    { "en": "makaino_ririmu", "cn": "魔界村莉莉姆" },
    { "en": "maki_(blue_archive)", "cn": "真纪（蔚蓝档案）" },
    { "en": "makigumo_(kancolle)", "cn": "卷云（舰队Collection）" },
    { "en": "makinami_mari_illustrious", "cn": "真中玛丽·光辉" },
    { "en": "makoto_nanaya", "cn": "七海真希" },
    { "en": "male_doctor_(arknights)", "cn": "男医生（明日方舟）" },
    { "en": "malenia_blade_of_miquella", "cn": "米凯拉之刃玛莲妮亚" },
    { "en": "mamiya_(kancolle)", "cn": "间宫（舰队Collection）" },
    { "en": "manaka_laala", "cn": "真中啦啦" },
    { "en": "manjuu_(azur_lane)", "cn": "蛮啾（碧蓝航线）" },
    { "en": "march_7th_(honkai:_star_rail)", "cn": "三月七（崩坏：星穹铁道）" },
    { "en": "march_7th_(preservation)_(honkai:_star_rail)", "cn": "三月七（存护）（崩坏：星穹铁道）" },
    { "en": "marcille_donato", "cn": "马克西尔·多纳托" },
    { "en": "mari_(track)_(blue_archive)", "cn": "玛丽（田径）（蔚蓝档案）" },
    { "en": "maria_cadenzavna_eve", "cn": "玛利亚·卡德扎夫娜·伊芙" },
    { "en": "marie_antoinette_(fate)", "cn": "玛丽·安托瓦内特（Fate）" },
    { "en": "marie_rose", "cn": "玛丽·萝丝" },
    { "en": "marth_(fire_emblem)", "cn": "马尔斯（火焰纹章）" },
    { "en": "martha_(fate)", "cn": "玛尔塔（Fate）" },
    { en: "maruzensky_(umamusume)", cn: "丸善斯基（赛马娘）" },
    { en: "mash_kyrielight", cn: "玛修·基列莱特" },
    { en: "mash_kyrielight_(dangerous_beast)", cn: "玛修·基列莱特（危险野兽）" },
    { en: "matikane_tannhauser_(umamusume)", cn: "谷野坦豪瑟（赛马娘）" },
    { en: "matikanefukukitaru_(umamusume)", cn: "谷野福来（赛马娘）" },
    { en: "matoba_risa", cn: "的场梨沙" },
    { en: "matsuno_todomatsu", cn: "松野十四松" },
    { en: "matsuura_kanan", cn: "松浦果南" },
    { en: "mavuika_(genshin_impact)", cn: "玛维卡（原神）" },
    { en: "may_(guilty_gear)", cn: "梅伊（罪恶装备）" },
    { en: "maya_(kancolle)", cn: "摩耶（舰队Collection）" },
    { en: "maya_kai_ni_(kancolle)", cn: "摩耶改二（舰队Collection）" },
    { en: "mayano_top_gun_(umamusume)", cn: "美浦波旁（赛马娘）" },
    { en: "mayuzumi_fuyuko", cn: "黛冬优子" },
    { en: "medb_(fate)", cn: "梅芙（命运）" },
    { en: "medea_(fate)", cn: "美狄亚（命运）" },
    { en: "medicine_melancholy", cn: "梅蒂欣·梅兰可莉" },
    { en: "medusa_(fate)", cn: "美杜莎（命运）" },
    { en: "mega_man_(character)", cn: "洛克人（角色）" },
    { en: "megumin", cn: "惠惠" },
    { en: "meisho_doto_(umamusume)", cn: "名将怒涛（赛马娘）" },
    { en: "mejiro_ardan_(umamusume)", cn: "目白阿尔丹（赛马娘）" },
    { en: "mejiro_dober_(umamusume)", cn: "目白多伯（赛马娘）" },
    { en: "mejiro_mcqueen_(umamusume)", cn: "目白麦昆（赛马娘）" },
    { en: "mejiro_palmer_(umamusume)", cn: "目白帕尔默（赛马娘）" },
    { en: "meltryllis_(fate)", cn: "梅尔特莉莉丝（命运）" },
    { en: "meltryllis_(swimsuit_lancer)_(fate)", cn: "梅尔特莉莉丝（泳装枪兵）（命运）" },
    { en: "meltryllis_(swimsuit_lancer)_(first_ascension)_(fate)", cn: "梅尔特莉莉丝（泳装枪兵）（第一阶段）（命运）" },
    { en: "melusine_(fate)", cn: "美露莘（命运）" },
    { en: "meowth", cn: "喵喵" },
    { en: "mercy_(overwatch)", cn: "天使（守望先锋）" },
    { en: "merlin_(fate)", cn: "梅林（命运）" },
    { en: "merlin_(fate/prototype)", cn: "梅林（命运/原型）" },
    { en: "merlin_prismriver", cn: "梅露兰·普莉兹姆利巴" },
    { en: "mew_(pokemon)", cn: "梦幻（宝可梦）" },
    { en: "micaiah_(fire_emblem)", cn: "米卡娅（火焰纹章）" },
    { en: "michishio_(kancolle)", cn: "满潮（舰队Collection）" },
    { en: "midori_(blue_archive)", cn: "绿（蔚蓝档案）" },
    { en: "mihono_bourbon_(umamusume)", cn: "美浦波旁（赛马娘）" },
    { en: "mika_(blue_archive)", cn: "美咲（蔚蓝档案）" },
    { en: "mikazuki_munechika", cn: "三日月宗近" },
    { en: "mima_(touhou)", cn: "魅魔（东方Project）" },
    { en: "mimura_kanako", cn: "三村かな子" },
    { en: "minami_kotori", cn: "南小鸟" },
    { en: "minamino_kanade", cn: "南野奏" },
    { en: "minamoto_no_raikou_(fate)", cn: "源赖光（命运）" },
    { en: "minamoto_sakura", cn: "源樱" },
    { en: "minato_aqua", cn: "凑阿库娅" },
    { en: "minato_aqua_(1st_costume)", cn: "凑阿库娅（第一服装）" },
    { en: "mio_(xenoblade)", cn: "米菈（异度之刃）" },
    { en: "mioda_ibuki", cn: "澪田伊吹" },
    { en: "miorine_rembran", cn: "米奥莉奈·连布兰" },
    { en: "miyako_(blue_archive)", cn: "宫子（蔚蓝档案）" },
    { en: "miyako_(swimsuit)_(blue_archive)", cn: "宫子（泳装）（蔚蓝档案）" },
    { en: "miyamoto_musashi_(fate)", cn: "宫本武藏（命运）" },
    { en: "miyamoto_musashi_(swimsuit_berserker)_(fate)", cn: "宫本武藏（泳装狂战士）（命运）" },
    { en: "miyamoto_musashi_(swimsuit_berserker)_(second_ascension)_(fate)", cn: "宫本武藏（泳装狂战士）（第二阶段）（命运）" },
    { en: "miyashita_ai", cn: "宫下爱" },
    { en: "miyu_(swimsuit)_(blue_archive)", cn: "美优（泳装）（蔚蓝档案）" },
    { en: "mizunashi_akari", cn: "水无灯里" },
    { en: "mizuno_ai", cn: "水野爱" },
    { en: "mizuno_ami", cn: "水野亚美" },
    { en: "mobius_(honkai_impact)", cn: "莫比乌斯（崩坏3）" },
    { en: "mococo_abyssgard", cn: "莫可可·深渊守卫" },
    { en: "mococo_abyssgard_(1st_costume)", cn: "莫可可·深渊守卫（第一服装）" },
    { en: "moe_(blue_archive)", cn: "萌（蔚蓝档案）" },
    { en: "momo_velia_deviluke", cn: "梦梦·贝莉雅·戴比路克" },
    { en: "momoe_nagisa", cn: "百江渚" },
    { en: "momoi_(blue_archive)", cn: "桃井（蔚蓝档案）" },
    { en: "momosuzu_nene", cn: "桃铃音音" },
    { en: "momozono_love", cn: "桃园爱" },
    { en: "monika_(doki_doki_literature_club)", cn: "莫妮卡（心跳文学部）" },
    { en: "monokuma", cn: "黑白熊" },
    { en: "monomi_(danganronpa)", cn: "黑白美（弹丸论破）" },
    { en: "moogle", cn: "莫古力" },
    { en: "moona_hoshinova", cn: "穆娜·霍希诺娃" },
    { en: "mordred_(fate)", cn: "莫德雷德（命运）" },
    { en: "mordred_(fate/apocrypha)", cn: "莫德雷德（命运/外典）" },
    { en: "morgan_le_fay_(fate)", cn: "摩根·勒·费伊（命运）" },
    { en: "mori_calliope", cn: "森美声" },
    { en: "mori_calliope_(1st_costume)", cn: "森美声（第一服装）" },
    { en: "mori_calliope_(streetwear)", cn: "森美声（街头服装）" },
    { en: "moroboshi_kirari", cn: "诸星琪拉莉" },
    { en: "morrigan_aensland", cn: "莫莉卡·安斯兰" },
    { en: "mortis_(bang_dream!)", cn: "莫蒂斯（BanG Dream!）" },
    { en: "mostima_(arknights)", cn: "莫斯提马（明日方舟）" },
    { en: "motoori_kosuzu", cn: "本居小铃" },
    { en: "mountain_(arknights)", cn: "山（明日方舟）" },
    { en: "mr._c.b._(umamusume)", cn: "C.B.（赛马娘）" },
    { en: "mualani_(genshin_impact)", cn: "穆阿兰尼（原神）" },
    { en: "mudkip", cn: "水跃鱼" },
    { en: "mudrock_(arknights)", cn: "泥岩（明日方舟）" },
    { en: "muelsyse_(arknights)", cn: "缪尔赛思（明日方舟）" },
    { en: "murakumo_kai_ni_(kancolle)", cn: "丛云改二（舰队Collection）" },
    { en: "murano_sayaka", cn: "村野纱耶香" },
    { en: "murasaki_shikibu_(fate)", cn: "紫式部（命运）" },
    { en: "murasaki_shion", cn: "紫咲诗音" },
    { en: "murasaki_shion_(1st_costume)", cn: "紫咲诗音（第一服装）" },
    { en: "murasame_(kancolle)", cn: "村雨（舰队Collection）" },
    { en: "murasame_kai_ni_(kancolle)", cn: "村雨改二（舰队Collection）" },
    { en: "mutsu_(kancolle)", cn: "陆奥（舰队Collection）" },
    { en: "mutsuki_(blue_archive)", cn: "睦月（蔚蓝档案）" },
    { en: "mysterious_heroine_x_alter_(fate)", cn: "谜之女主角X Alter（命运）" },
    { en: "mysterious_heroine_xx_(fate)", cn: "谜之女主角XX（命运）" },
    { en: "n_(pokemon)", cn: "N（宝可梦）" },
    { en: "nachi_(kancolle)", cn: "那智（舰队Collection）" },
    { en: "nagato_(azur_lane)", cn: "长门（碧蓝航线）" },
    { en: "nagi_(kannagi)", cn: "柊（神薙）" },
    { en: "nagisa_(blue_archive)", cn: "渚（蔚蓝档案）" },
    { en: "nagisa_kaworu", cn: "渚薰" },
    { en: "nahida_(genshin_impact)", cn: "纳西妲（原神）" },
    { en: "nakamura_yuri", cn: "中村百合" },
    { en: "nakano_itsuki", cn: "中野五月" },
    { en: "nakano_yotsuba", cn: "中野四叶" },
    { en: "nakiri_ayame", cn: "百鬼绫目" },
    { en: "nakiri_ayame_(1st_costume)", cn: "百鬼绫目（第一服装）" },
    { en: "nanao_yuriko", cn: "七尾百合子" },
    { en: "nanashi_mumei_(1st_costume)", cn: "无名（第一服装）" },
    { en: "narita_brian_(umamusume)", cn: "成田白仁（赛马娘）" },
    { en: "narita_taishin_(umamusume)", cn: "成田大进（赛马娘）" },
    { en: "narita_top_road_(umamusume)", cn: "成田顶级路（赛马娘）" },
    { en: "narmaya_(granblue_fantasy)", cn: "娜露梅亚（碧蓝幻想）" },
    { en: "natori_sana", cn: "名取纱那" },
    { en: "natsu_(blue_archive)", cn: "夏（蔚蓝档案）" },
    { en: "natsuiro_matsuri", cn: "夏色祭" },
    { en: "natsuki_(doki_doki_literature_club)", cn: "夏树（心跳文学部）" },
    { en: "natsuki_subaru", cn: "菜月昴" },
    { en: "natsume_rin", cn: "夏目铃" },
    { en: "navia_(genshin_impact)", cn: "纳维亚（原神）" },
    { en: "nearl_(arknights)", cn: "临光（明日方舟）" },
    { en: "nekomata_okayu", cn: "猫又小粥" },
    { en: "nekomata_okayu_(1st_costume)", cn: "猫又小粥（第一服装）" },
    { en: "nekomata_okayu_(oversized_shirt)", cn: "猫又小粥（超大衬衫）" },
    { en: "nekomusume", cn: "猫娘" },
    { en: "nemoto_hina", cn: "根本日向" },
    { en: "nepgear", cn: "涅普姬雅" },
    { en: "neptune_(neptunia)", cn: "涅普顿（超次元游戏海王星）" },
    { en: "nerissa_ravencroft", cn: "内莉莎·瑞文克罗夫特" },
    { en: "nerissa_ravencroft_(1st_costume)", cn: "内莉莎·瑞文克罗夫特（第一服装）" },
    { en: "nero_claudius_(fate)", cn: "尼禄·克劳狄乌斯（命运）" },
    { en: "nero_claudius_(fate/extra)", cn: "尼禄·克劳狄乌斯（命运/EXTRA）" },
    { en: "nero_claudius_(swimsuit_caster)_(fate)", cn: "尼禄·克劳狄乌斯（泳装术士）（命运）" },
    { en: "new_jersey_(azur_lane)", cn: "新泽西（碧蓝航线）" },
    { en: "nia_(blade)_(xenoblade)", cn: "尼亚（异刃）（异度之刃）" },
    { en: "nia_(xenoblade)", cn: "尼亚（异度之刃）" },
    { en: "nia_teppelin", cn: "尼亚·特佩林" },
    { en: "nian_(arknights)", cn: "年（明日方舟）" },
    { en: "nice_nature_(umamusume)", cn: "好天资（赛马娘）" },
    { en: "nicole_demara", cn: "妮可·德马拉" },
    { en: "nijigaoka_mashiro", cn: "虹之咲真白" },
    { en: "nilou_(genshin_impact)", cn: "妮露（原神）" },
    { en: "ningguang_(genshin_impact)", cn: "凝光（原神）" },
    { en: "ninomae_ina'nis", cn: "一伊那尔栖" },
    { en: "ninomae_ina'nis_(1st_costume)", cn: "一伊那尔栖（第一套服装）" },
    { en: "nishikigi_chisato", cn: "锦木千束" },
    { en: "niwatari_kutaka", cn: "丹羽凪鹰" },
    { en: "noa_(blue_archive)", cn: "诺亚（蔚蓝档案）" },
    { en: "noel_vermillion", cn: "诺艾尔·弗米利昂" },
    { en: "noelle_(genshin_impact)", cn: "诺艾尔（原神）" },
    { en: "noire_(neptunia)", cn: "黑色之心（海王星）" },
    { en: "nonomi_(blue_archive)", cn: "诺诺米（蔚蓝档案）" },
    { en: "nonomi_(swimsuit)_(blue_archive)", cn: "诺诺米（泳装）（蔚蓝档案）" },
    { en: "noshiro_(kancolle)", cn: "能代（舰队Collection）" },
    { en: "noumi_kudryavka", cn: "能美·库特莉亚芙卡" },
    { en: "nowaki_(kancolle)", cn: "野分（舰队Collection）" },
    { en: "nozomi_(blue_archive)", cn: "望（蔚蓝档案）" },
    { en: "nu-13", cn: "Nu-13" },
    { en: "nursery_rhyme_(fate)", cn: "童谣（Fate）" },
    { en: "oberon_(fate)", cn: "奥伯龙（Fate）" },
    { en: "oberon_(third_ascension)_(fate)", cn: "奥伯龙（三破）（Fate）" },
    { en: "oblivionis_(bang_dream!)", cn: "奥比利奥尼斯（BanG Dream!）" },
    { en: "oda_nobunaga_(fate)", cn: "织田信长（Fate）" },
    { en: "oda_nobunaga_(koha-ace)", cn: "织田信长（Fate/KOHA-ACE）" },
    { en: "oguri_cap_(umamusume)", cn: "小栗帽（赛马娘）" },
    { en: "ohara_mari", cn: "小原鞠莉" },
    { en: "ohtsuki_yui", cn: "大月由衣" },
    { en: "okita_souji_(koha-ace)", cn: "冲田总司（Fate/KOHA-ACE）" },
    { en: "okita_souji_alter_(fate)", cn: "冲田总司Alter（Fate）" },
    { en: "olimar", cn: "奥利玛" },
    { en: "omaru_polka", cn: "尾丸波尔卡" },
    { en: "ookami_mio", cn: "大神澪" },
    { en: "ookami_mio_(1st_costume)", cn: "大神澪（第一套服装）" },
    { en: "ookami_mio_(casual)", cn: "大神澪（休闲装）" },
    { en: "oomuro_sakurako", cn: "大室樱子" },
    { en: "ooshio_(kancolle)", cn: "大潮（舰队Collection）" },
    { en: "oozora_subaru", cn: "大空昴" },
    { en: "oreki_houtarou", cn: "折木奉太郎" },
    { en: "osaka_shizuku", cn: "大阪静" },
    { en: "osakabehime_(fate)", cn: "刑部姬（Fate）" },
    { en: "osaki_amana", cn: "大崎天娜" },
    { en: "osaki_tenka", cn: "大崎天香" },
    { en: "osawa_rurino", cn: "大泽瑠璃乃" },
    { en: "oshida_(girls_und_panzer)", cn: "大岛（少女与战车）" },
    { en: "oshino_shinobu", cn: "忍野忍" },
    { en: "otomune_kozue", cn: "音无小梢" },
    { en: "oumae_kumiko", cn: "黄前久美子" },
    { en: "ouro_kronii_(1st_costume)", cn: "时间守护者Kronii（第一套服装）" },
    { en: "oyama_mahiro", cn: "大室真寻" },
    { en: "oyama_mihari", cn: "大室三春" },
    { en: "palutena", cn: "帕露缇娜" },
    { en: "passionlip_(fate)", cn: "热情之唇（Fate）" },
    { en: "pavolia_reine", cn: "帕沃莉亚·蕾妮" },
    { en: "pecorine_(princess_connect!)", cn: "佩可莉姆（公主连结！）" },
    { en: "pekomama", cn: "佩可妈妈" },
    { en: "pekomon_(usada_pekora)", cn: "佩可萌（兔田佩克拉）" },
    { en: "pepperoni_(girls_und_panzer)", cn: "佩珀罗尼（少女与战车）" },
    { en: "peroro_(blue_archive)", cn: "佩罗罗（蔚蓝档案）" },
    { en: "perrine_h._clostermann", cn: "佩琳·克洛斯特曼" },
    { en: "phosphophyllite", cn: "磷叶石" },
    { en: "pit_(kid_icarus)", cn: "皮特（卡比之镜）" },
    { en: "plana_(blue_archive)", cn: "普拉娜（蔚蓝档案）" },
    { en: "platinum_(arknights)", cn: "白金（明日方舟）" },
    { en: "pochita_(chainsaw_man)", cn: "波奇塔（电锯人）" },
    { en: "pod_(nier:automata)", cn: "辅助机器人（尼尔：自动人形）" },
    { en: "pola_(kancolle)", cn: "波拉（舰队Collection）" },
    { en: "pomu_rainpuff", cn: "波姆·雨团" },
    { en: "popuko", cn: "POP子" },
    { en: "power_(chainsaw_man)", cn: "帕瓦（电锯人）" },
    { en: "pramanix_(arknights)", cn: "普拉尼克斯（明日方舟）" },
    { en: "princess_king_boo", cn: "布公主" },
    { en: "prinz_eugen_(azur_lane)", cn: "欧根亲王（碧蓝航线）" },
    { en: "prinz_eugen_(kancolle)", cn: "欧根亲王（舰队Collection）" },
    { en: "prinz_eugen_(unfading_smile)_(azur_lane)", cn: "欧根亲王（永恒微笑）（碧蓝航线）" },
    { en: "prisma_illya", cn: "魔法少女伊莉雅" },
    { en: "professor_niyaniya_(blue_archive)", cn: "仁耶尼亚教授（蔚蓝档案）" },
    { en: "protagonist_3_(housamo)", cn: "主角3（神威启示录）" },
    { en: "purple_heart_(neptunia)", cn: "紫心（海王星）" },
    { en: "pyonta", cn: "皮昂塔" },
    { en: "qingyi_(zenless_zone_zero)", cn: "青衣（绝区零）" },
    { en: "qiqi_(genshin_impact)", cn: "七七（原神）" },
    { en: "rabbit_yukine", cn: "兔子雪音" },
    { en: "rachel_alucard", cn: "雷切尔·阿鲁卡德" },
    { en: "racing_miku", cn: "赛车初音" },
    { en: "raiden_mei", cn: "雷电芽衣" },
    { en: "raiden_mei_(herrscher_of_thunder)", cn: "雷电芽衣（雷之律者）" },
    { en: "raiden_shogun", cn: "雷电将军" },
    { en: "raising_heart", cn: "升腾之心" },
    { en: "ram_(re:zero)", cn: "拉姆（Re:从零开始的异世界生活）" },
    { en: "ranka_lee", cn: "兰卡·李" },
    { en: "ranni_the_witch", cn: "魔女兰尼" },
    { en: "raora_panthera", cn: "劳拉·潘特拉" },
    { en: "raphtalia", cn: "拉芙塔莉雅" },
    { en: "rapi_(nikke)", cn: "拉比（妮姬）" },
    { en: "re-class_battleship", cn: "Re级战舰" },
    { en: "rebecca_(cyberpunk)", cn: "丽贝卡（赛博朋克）" },
    { en: "red_pikmin", cn: "红色皮克敏" },
    { en: "reisa_(blue_archive)", cn: "蕾莎（蔚蓝档案）" },
    { en: "reisalin_stout", cn: "莱莎琳·斯托特" },
    { en: "reizei_mako", cn: "冷泉麻子" },
    { en: "rem_(re:zero)", cn: "雷姆（Re:从零开始的异世界生活）" },
    { en: "rensouhou-chan", cn: "连装炮酱" },
    { en: "rensouhou-kun", cn: "连装炮君" },
    { en: "rex_(xenoblade)", cn: "雷克斯（异度神剑）" },
    { en: "reze_(chainsaw_man)", cn: "蕾塞（电锯人）" },
    { en: "richelieu_(kancolle)", cn: "黎塞留（舰队Collection）" },
    { en: "riesz", cn: "莉丝" },
    { en: "rika_(pokemon)", cn: "莉佳（宝可梦）" },
    { en: "rimuru_tempest", cn: "利姆路·坦派斯特" },
    { en: "ringo_(touhou)", cn: "铃仙（东方Project）" },
    { en: "rio_(blue_archive)", cn: "里屋（蔚蓝档案）" },
    { en: "rita_rossweisse", cn: "丽塔·洛丝薇瑟" },
    { en: "robin_(female)_(fire_emblem)", cn: "罗宾（女）（火焰纹章）" },
    { en: "robin_(fire_emblem)", cn: "罗宾（火焰纹章）" },
    { en: "robin_(honkai:_star_rail)", cn: "罗宾（崩坏：星穹铁道）" },
    { en: "roll_(mega_man)", cn: "萝儿（洛克人）" },
    { en: "rosa_(pokemon)", cn: "罗莎（宝可梦）" },
    { en: "rosalina", cn: "罗莎塔" },
    { en: "rosaria_(genshin_impact)", cn: "罗莎莉亚（原神）" },
    { en: "rosmontis_(arknights)", cn: "罗丝蒙特（明日方舟）" },
    { en: "rotom", cn: "洛托姆" },
    { en: "rotom_phone", cn: "洛托姆手机" },
    { en: "rover_(wuthering_waves)", cn: "漫游者（Wuthering Waves）" },
    { en: "rowlet", cn: "木木枭" },
    { en: "roxy_migurdia", cn: "洛琪希·米格路迪亚" },
    { en: "rpk-16_(girls'_frontline)", cn: "RPK-16（少女前线）" },
    { en: "ru-class_battleship", cn: "Ru级战舰" },
    { en: "ruan_mei_(honkai:_star_rail)", cn: "阮梅（崩坏：星穹铁道）" },
    { en: "rydia_(ff4)", cn: "莉迪亚（最终幻想IV）" },
    { en: "ryougi_shiki", cn: "两仪式" },
    { en: "ryuujou_(kancolle)", cn: "龙骧（舰队Collection）" },
    { en: "saber_(fate)", cn: "阿尔托莉雅·潘德拉贡（Fate）" },
    { en: "saber_alter", cn: "黑Saber（Fate）" },
    { en: "saber_lily", cn: "阿尔托莉雅·潘德拉贡（Lily）" },
    { en: "sagisawa_fumika", cn: "狭雾文香" },
    { en: "sailor_jupiter", cn: "水手木星" },
    { en: "sailor_mars", cn: "水手火星" },
    { en: "sailor_mercury", cn: "水手水星" },
    { en: "sailor_moon", cn: "水手月亮" },
    { en: "sailor_venus", cn: "水手金星" },
    { en: "sakamata_chloe", cn: "乃木若叶" },
    { en: "sakamata_chloe_(1st_costume)", cn: "乃木若叶（第一套服装）" },
    { en: "sakata_gintoki", cn: "坂田银时" },
    { en: "sakura_chiyono_o_(umamusume)", cn: "樱花千代子（赛马娘）" },
    { en: "sakura_futaba", cn: "樱花双叶" },
    { en: "sakura_miko", cn: "樱花美子" },
    { en: "sakura_miko_(1st_costume)", cn: "樱花美子（第一套服装）" },
    { en: "sakura_miko_(casual)", cn: "樱花美子（休闲装）" },
    { en: "sakura_miku", cn: "樱花初音" },
    { en: "sakuragi_mano", cn: "樱木真乃" },
    { en: "sakurai_momoka", cn: "樱井桃子" },
    { en: "sakurajima_mai", cn: "樱花岛舞" },
    { en: "sakurako_(blue_archive)", cn: "樱子（蔚蓝档案）" },
    { en: "sandalphon_(granblue_fantasy)", cn: "桑达芬（碧蓝幻想）" },
    { en: "sangonomiya_kokomi", cn: "珊瑚宫心海" },
    { en: "saori_(blue_archive)", cn: "沙织（蔚蓝档案）" },
    { en: "saratoga_(kancolle)", cn: "萨拉托加（舰队Collection）" },
    { en: "saren_(princess_connect!)", cn: "咲恋（公主连结！）" },
    { en: "saria_(arknights)", cn: "赛雷娅（明日方舟）" },
    { en: "sasaki_chie", cn: "佐佐木千惠" },
    { en: "sasaki_saku", cn: "佐佐木咲" },
    { en: "satonaka_chie", cn: "里中千惠" },
    { en: "satono_diamond_(umamusume)", cn: "佐藤钻石（赛马娘）" },
    { en: "satou_kazuma", cn: "佐藤和真" },
    { en: "satsuki_(kancolle)", cn: "皋月（舰队Collection）" },
    { en: "sawa_azusa", cn: "泽梓" },
    { en: "sazanami_(kancolle)", cn: "早波（舰队Collection）" },
    { en: "scathach_(fate)", cn: "斯卡哈（Fate）" },
    { en: "scathach_skadi_(fate)", cn: "斯卡蒂（Fate）" },
    { en: "schwarz_(arknights)", cn: "斯卡蒂（明日方舟）" },
    { en: "seele_vollerei", cn: "希儿·芙乐艾" },
    { en: "seia_(blue_archive)", cn: "希亚（蔚蓝档案）" },
    { en: "seiran_(touhou)", cn: "青兰（东方Project）" },
    { en: "seiun_sky_(umamusume)", cn: "星云天空（赛马娘）" },
    { en: "selen_tatsuki", cn: "星川龙（赛马娘）" },
    { en: "sendai_(kancolle)", cn: "仙台（舰队Collection）" },
    { en: "sendai_hakurei_no_miko", cn: "仙台白灵神社的巫女" },
    { en: "sendai_kai_ni_(kancolle)", cn: "仙台改二（舰队Collection）" },
    { en: "sengoku_nadeko", cn: "千石抚子" },
    { en: "senketsu", cn: "鲜血" },
    { en: "serena_(pokemon)", cn: "塞蕾娜（宝可梦）" },
    { en: "serika_(blue_archive)", cn: "芹香（蔚蓝档案）" },
    { en: "serizawa_asahi", cn: "芹泽旭" },
    { en: "shana", cn: "夏娜" },
    { en: "shenhe_(genshin_impact)", cn: "申鹤（原神）" },
    { en: "shibuya_kanon", cn: "涩谷花音" },
    { en: "shidare_hotaru", cn: "枝垂萤" },
    { en: "shigure_(blue_archive)", cn: "时雨（蔚蓝档案）" },
    { en: "shigure_kai_san_(kancolle)", cn: "时雨改三（舰队Collection）" },
    { en: "shigure_ui_(vtuber)", cn: "时雨羽衣（虚拟主播）" },
    { en: "shiina_taki", cn: "椎名立希" },
    { en: "shiina_yuika", cn: "椎名唯华" },
    { en: "shijou_takane", cn: "四条贵音" },
    { en: "shikanoin_heizou", cn: "鹿野院平藏" },
    { en: "shikinami_(kancolle)", cn: "岛风（舰队Collection）" },
    { en: "shimada_arisu", cn: "岛田爱丽丝" },
    { en: "shimamura_uzuki", cn: "岛村卯月" },
    { en: "shinano_(azur_lane)", cn: "信浓（碧蓝航线）" },
    { en: "shinki_(touhou)", cn: "神绮（东方Project）" },
    { en: "shinku", cn: "真红" },
    { en: "shinomiya_kaguya", cn: "四宫辉夜" },
    { en: "shinonome_akito", cn: "东云彰人" },
    { en: "shinonome_ena", cn: "东云绘名" },
    { en: "shinosawa_hiro", cn: "篠泽广" },
    { en: "shiomi_kotone", cn: "汐见琴音" },
    { en: "shiomi_syuko", cn: "汐见志子" },
    { en: "shirai_kuroko", cn: "白井黑子" },
    { en: "shirakami_fubuki", cn: "白上吹雪" },
    { en: "shirakami_fubuki_(1st_costume)", cn: "白上吹雪（第一套服装）" },
    { en: "shiranui_(kancolle)", cn: "不知火（舰队Collection）" },
    { en: "shiranui_flare", cn: "不知火芙蕾雅" },
    { en: "shiranui_mai", cn: "不知火舞" },
    { en: "shirase_sakuya", cn: "白濑咲夜" },
    { en: "shiratsuyu_(kancolle)", cn: "白露（舰队Collection）" },
    { en: "shirogane_noel", cn: "白银诺艾尔" },
    { en: "shirogane_noel_(1st_costume)", cn: "白银诺艾尔（第一套服装）" },
    { en: "shiroko_(blue_archive)", cn: "白子（蔚蓝档案）" },
    { en: "shiroko_(swimsuit)_(blue_archive)", cn: "白子（泳装）（蔚蓝档案）" },
    { en: "shiroko_terror_(blue_archive)", cn: "白子·恐怖（蔚蓝档案）" },
    { en: "shishiro_botan", cn: "紫咲诗音" },
    { en: "shishiro_botan_(1st_costume)", cn: "紫咲诗音（第一套服装）" },
    { en: "shokuhou_misaki", cn: "食蜂操祈" },
    { en: "shoukaku_(kancolle)", cn: "翔鹤（舰队Collection）" },
    { en: "shu_(arknights)", cn: "舒（明日方舟）" },
    { en: "shun_(blue_archive)", cn: "瞬（蔚蓝档案）" },
    { en: "shun_(small)_(blue_archive)", cn: "瞬（小）（蔚蓝档案）" },
    { en: "shuten_douji_(fate)", cn: "酒吞童子（Fate）" },
    { en: "sieg_(fate)", cn: "齐格（Fate）" },
    { en: "siege_(arknights)", cn: "推进之王（明日方舟）" },
    { en: "sigewinne_(genshin_impact)", cn: "希格雯（原神）" },
    { en: "signum", cn: "希格诺" },
    { en: "silence_(arknights)", cn: "闪灵（明日方舟）" },
    { en: "silence_suzuka_(umamusume)", cn: "无声铃鹿（赛马娘）" },
    { en: "silica", cn: "西莉卡" },
    { en: "silver_wolf_(honkai:_star_rail)", cn: "银狼（崩坏：星穹铁道）" },
    { en: "simon_(ttgl)", cn: "西蒙（天元突破）" },
    { en: "sinclair_(project_moon)", cn: "辛克莱（Project Moon）" },
    { en: "sirius_(azur_lane)", cn: "天狼星（碧蓝航线）" },
    { en: "sirius_symboli_(umamusume)", cn: "天狼星象征（赛马娘）" },
    { en: "sister_claire", cn: "修女克莱尔" },
    { en: "skadi_(arknights)", cn: "斯卡蒂（明日方舟）" },
    { en: "skadi_the_corrupting_heart_(arknights)", cn: "浊心斯卡蒂（明日方舟）" },
    { en: "slime_(dragon_quest)", cn: "史莱姆（勇者斗恶龙）" },
    { en: "slime_(genshin_impact)", cn: "史莱姆（原神）" },
    { en: "smart_falcon_(umamusume)", cn: "聪明猎鹰（赛马娘）" },
    { en: "snivy", cn: "藤藤蛇" },
    { en: "sobble", cn: "泪眼蜥" },
    { en: "sona_(league_of_legends)", cn: "娑娜（英雄联盟）" },
    { en: "sonia_nevermind", cn: "索尼娅·内瓦蒙德" },
    { en: "sonoda_chiyoko", cn: "园田千代子" },
    { en: "sonozaki_mion", cn: "园崎魅音" },
    { en: "sonozaki_shion", cn: "园崎诗音" },
    { en: "sonya_(kill_me_baby)", cn: "索尼娅（爱杀宝贝）" },
    { en: "sora_harewataru", cn: "空晴渡" },
    { en: "sorceress_(dragon's_crown)", cn: "女巫（龙之皇冠）" },
    { en: "soukaku_(zenless_zone_zero)", cn: "双鹤（绝区零）" },
    { en: "souryuu_(kancolle)", cn: "苍龙（舰队Collection）" },
    { en: "souryuu_asuka_langley", cn: "惣流·明日香·兰格雷" },
    { en: "souseiseki", cn: "翠星石" },
    { en: "sparkle_(honkai:_star_rail)", cn: "星火（崩坏：星穹铁道）" },
    { en: "special_week_(umamusume)", cn: "特别周（赛马娘）" },
    { en: "specter_(arknights)", cn: "幽灵鲨（明日方舟）" },
    { en: "springfield_(girls'_frontline)", cn: "春田（少女前线）" },
    { en: "st._louis_(azur_lane)", cn: "圣路易斯（碧蓝航线）" },
    { en: "st_ar-15_(girls'_frontline)", cn: "ST AR-15（少女前线）" },
    { en: "star_sapphire", cn: "星蓝宝石" },
    { en: "stark_(sousou_no_frieren)", cn: "斯塔克（葬送的芙莉莲）" },
    { en: "stelle_(honkai:_star_rail)", cn: "星（崩坏：星穹铁道）" },
    { en: "subaru_nakajima", cn: "中岛昴" },
    { en: "sucrose_(genshin_impact)", cn: "砂糖（原神）" },
    { en: "suigintou", cn: "水银灯" },
    { en: "suiseiseki", cn: "翠星石" },
    { en: "sukoya_kana", cn: "须古小夜" },
    { en: "sukuna_shinmyoumaru", cn: "少名针妙丸" },
    { en: "sunazuka_akira", cn: "砂冢明" },
    { en: "sunday_(honkai:_star_rail)", cn: "星期日（崩坏：星穹铁道）" },
    { en: "sunny_milk", cn: "桑尼米尔克" },
    { en: "suomi_(girls'_frontline)", cn: "索米（少女前线）" },
    { en: "suou_momoko", cn: "周防桃子" },
    { en: "super_creek_(umamusume)", cn: "超级小溪（赛马娘）" },
    { en: "surtr_(arknights)", cn: "史尔特尔（明日方舟）" },
    { en: "sussurro_(arknights)", cn: "絮语（明日方舟）" },
    { en: "suzuhara_lulu", cn: "铃原露露" },
    { en: "suzukaze_aoba", cn: "凉风青叶" },
    { en: "suzuran_(arknights)", cn: "铃兰（明日方舟）" },
    { en: "suzutsuki_(kancolle)", cn: "凉月（舰队Collection）" },
    { en: "suzuya_(kancolle)", cn: "铃谷（舰队Collection）" },
    { en: "suzuya_kai_ni_(kancolle)", cn: "铃谷改二（舰队Collection）" },
    { en: "sweep_tosho_(umamusume)", cn: "清扫图书（赛马娘）" },
    { en: "swire_(arknights)", cn: "斯维尔（明日方舟）" },
    { en: "sylphiette_(mushoku_tensei)", cn: "西尔菲（无职转生）" },
    { en: "sylveon", cn: "仙子伊布" },
    { en: "symboli_rudolf_(umamusume)", cn: "象征鲁道夫（赛马娘）" },
    { en: "t-head_admiral", cn: "T字头提督" },
    { en: "t-head_trainer_(umamusume)", cn: "T字头训练师（赛马娘）" },
    { en: "t.m._opera_o_(umamusume)", cn: "T.M.歌剧王（赛马娘）" },
    { en: "ta-class_battleship", cn: "Ta级战舰" },
    { en: "tachibana_arisu", cn: "橘爱丽丝" },
    { en: "tachibana_hibiki_(symphogear)", cn: "立花响（战姬绝唱）" },
    { en: "tachibana_kanade", cn: "立花奏" },
    { en: "taigei_(kancolle)", cn: "大鲸（舰队Collection）" },
    { en: "taihou_(azur_lane)", cn: "大凤（碧蓝航线）" },
    { en: "taihou_(kancolle)", cn: "大凤（舰队Collection）" },
    { en: "tails_(sonic)", cn: "塔尔斯（索尼克）" },
    { en: "takagaki_kaede", cn: "高垣枫" },
    { en: "takamaki_anne", cn: "高卷杏" },
    { en: "takamatsu_tomori", cn: "高松灯" },
    { en: "takanashi_kiara", cn: "小鸟游琪亚拉" },
    { en: "takanashi_kiara_(1st_costume)", cn: "小鸟游琪亚拉（第一套服装）" },
    { en: "takane_lui", cn: "高岭露依" },
    { en: "takane_lui_(1st_costume)", cn: "高岭露依（第一套服装）" },
    { en: "takao_(azur_lane)", cn: "高雄（碧蓝航线）" },
    { en: "takara_miyuki", cn: "宝拉美雪" },
    { en: "takasaki_yu", cn: "高崎悠" },
    { en: "takatsuki_yayoi", cn: "高槻弥生" },
    { en: "takeba_yukari", cn: "竹场由香里" },
    { en: "takebe_saori", cn: "武部沙织" },
    { en: "takeda_harumi", cn: "武田晴海" },
    { en: "takodachi_(ninomae_ina'nis)", cn: "章鱼烧（一伊那尔栖）" },
    { en: "tama_(kancolle)", cn: "球磨（舰队Collection）" },
    { en: "tamaki_iroha", cn: "环伊吕波" },
    { en: "tamamo_(fate)", cn: "玉藻前（Fate）" },
    { en: "tamamo_cat_(fate)", cn: "玉藻猫（Fate）" },
    { en: "tamamo_cross_(umamusume)", cn: "玉藻十字（赛马娘）" },
    { en: "tamamo_no_mae_(fate/extra)", cn: "玉藻前（Fate/EXTRA）" },
    { en: "tamamo_no_mae_(swimsuit_lancer)_(fate)", cn: "玉藻前（泳装枪阶）（Fate）" },
    { en: "tang_keke", cn: "唐可可" },
    { en: "tartaglia_(genshin_impact)", cn: "达达利亚（原神）" },
    { en: "tatsuta_(kancolle)", cn: "龙田（舰队Collection）" },
    { en: "tedeza_rize", cn: "蒂德莎·莉兹" },
    { en: "tenkyuu_chimata", cn: "天弓千亦" },
    { en: "tenma_tsukasa", cn: "天马司" },
    { en: "tennoji_rina", cn: "天王寺璃奈" },
    { en: "tenochtitlan_(fate)", cn: "特诺奇蒂特兰（Fate）" },
    { en: "tepig", cn: "暖暖猪" },
    { en: "terra_branford", cn: "蒂娜·布兰佛德" },
    { en: "texas_the_omertosa_(arknights)", cn: "德克萨斯·沉默者（明日方舟）" },
    { en: "tharja_(fire_emblem)", cn: "萨莉亚（火焰纹章）" },
    { en: "the_herta_(honkai:_star_rail)", cn: "赫尔塔（崩坏：星穹铁道）" },
    { en: "theresa_apocalypse", cn: "德丽莎·阿波卡利斯" },
    { en: "tifa_lockhart", cn: "蒂法·洛克哈特" },
    { en: "tighnari_(genshin_impact)", cn: "提纳里（原神）" },
    { en: "tiki_(fire_emblem)", cn: "琪琪（火焰纹章）" },
    { en: "tippy_(gochiusa)", cn: "提比（请问您今天要来点兔子吗？）" },
    { en: "toga_himiko", cn: "渡我被身子" },
    { en: "togawa_sakiko", cn: "户川咲子" },
    { en: "tohru_(maidragon)", cn: "托尔（小林家的龙女仆）" },
    { en: "tohsaka_rin", cn: "远坂凛" },
    { en: "tohsaka_tokiomi", cn: "远坂时臣" },
    { en: "tokai_teio_(umamusume)", cn: "东海帝王（赛马娘）" },
    { en: "toki_(blue_archive)", cn: "时（蔚蓝档案）" },
    { en: "toki_(bunny)_(blue_archive)", cn: "时（兔女郎）（蔚蓝档案）" },
    { en: "tokiko_(touhou)", cn: "朱鹭子（东方Project）" },
    { en: "tokino_sora", cn: "时乃空" },
    { en: "tokisaki_kurumi", cn: "时崎狂三" },
    { en: "tokitsukaze_(kancolle)", cn: "时津风（舰队Collection）" },
    { en: "tokoyami_towa", cn: "常暗永远" },
    { en: "tokoyami_towa_(1st_costume)", cn: "常暗永远（第一套服装）" },
    { en: "tokoyami_towa_(jirai_kei)", cn: "常暗永远（地雷系）" },
    { en: "tomoe_gozen_(fate)", cn: "巴御前（Fate）" },
    { en: "tone_(kancolle)", cn: "利根（舰队Collection）" },
    { en: "tony_tony_chopper", cn: "托尼托尼·乔巴" },
    { en: "topaz_(honkai:_star_rail)", cn: "托帕（崩坏：星穹铁道）" },
    { en: "toshinou_kyouko", cn: "东云京子" },
    { en: "totoki_airi", cn: "十道爱莉" },
    { en: "touhoku_kiritan", cn: "东北切蒲英" },
    { en: "toutetsu_yuuma", cn: "斗铁勇马" },
    { en: "tsukikage_yuri", cn: "月影尤里" },
    { en: "tsukino_mito_(1st_costume)", cn: "月野美冬（第一套服装）" },
    { en: "tsukino_usagi", cn: "月野兔" },
    { en: "tsukioka_kogane", cn: "月岡小奏" },
    { en: "tsukishiro_yanagi", cn: "月白柳" },
    { en: "tsukumo_benben", cn: "九十九弁弁" },
    { en: "tsukumo_sana", cn: "九十九佐奈" },
    { en: "tsukumo_yatsuhashi", cn: "九十九八桥" },
    { en: "tsukuyomi_shirabe", cn: "月読调" },
    { en: "tsunade_(naruto)", cn: "纲手（火影忍者）" },
    { en: "tsunomaki_watame", cn: "角巻綿芽" },
    { en: "tsurumaki_maki", cn: "弦巻真紀" },
    { en: "tsurumaru_kuninaga", cn: "鹤丸国永" },
    { en: "tsushima_yoshiko", cn: "津島善子" },
    { en: "twilight_(spy_x_family)", cn: "黄昏（间谍过家家）" },
    { en: "twin_turbo_(umamusume)", cn: "双涡轮（赛马娘）" },
    { en: "u-511_(kancolle)", cn: "U-511（舰队Collection）" },
    { en: "ubel_(sousou_no_frieren)", cn: "乌贝（葬送的芙莉莲）" },
    { en: "uehara_ayumu", cn: "上原步梦" },
    { en: "ui_(blue_archive)", cn: "优衣（蔚蓝档案）" },
    { en: "ujimatsu_chiya", cn: "宇治松千夜" },
    { en: "ultimate_madoka", cn: "终极圆神" },
    { en: "umbreon", cn: "月伊布" },
    { en: "umikaze_(kancolle)", cn: "海风（舰队Collection）" },
    { en: "ump45_(girls'_frontline)", cn: "UMP45（少女前线）" },
    { en: "ump9_(girls'_frontline)", cn: "UMP9（少女前线）" },
    { en: "unicorn_(azur_lane)", cn: "独角兽（碧蓝航线）" },
    { en: "unryuu_(kancolle)", cn: "云龙（舰队Collection）" },
    { en: "unzan", cn: "云山" },
    { en: "urakaze_(kancolle)", cn: "浦风（舰队Collection）" },
    { en: "uruha_rushia", cn: "润羽露西娅" },
    { en: "uruha_rushia_(1st_costume)", cn: "润羽露西娅（第一套服装）" },
    { en: "uryuu_ryuunosuke", cn: "雨龙龙之介" },
    { en: "usada_pekora_(1st_costume)", cn: "兔田佩克拉（第一套服装）" },
    { en: "usami_sumireko", cn: "宇佐美すみれ子" },
    { en: "ushiwakamaru_(fate)", cn: "牛若丸（Fate）" },
    { en: "usopp", cn: "乌索普" },
    { en: "utage_(arknights)", cn: "宴（明日方舟）" },
    { en: "utsugi_noriyuki", cn: "宇津木徳幸" },
    { en: "uzuki_(kancolle)", cn: "卯月（舰队Collection）" },
    { en: "vaporeon", cn: "水伊布" },
    { en: "verniy_(kancolle)", cn: "信赖（舰队Collection）" },
    { en: "verxina_(umamusume)", cn: "维西娜（赛马娘）" },
    { en: "vikala_(granblue_fantasy)", cn: "维卡拉（碧蓝幻想）" },
    { en: "viktor_nikiforov", cn: "维克托·尼基福罗夫" },
    { en: "violet_evergarden", cn: "薇尔莉特·伊芙加登" },
    { en: "virtuosa_(arknights)", cn: "维图萨（明日方舟）" },
    { en: "vita_(nanoha)", cn: "维塔（魔法少女奈叶）" },
    { en: "vivio", cn: "薇薇欧" },
    { en: "vivlos_(umamusume)", cn: "维夫洛斯（赛马娘）" },
    { en: "vodka_(umamusume)", cn: "伏特加（赛马娘）" },
    { en: "w_(arknights)", cn: "W（明日方舟）" },
    { en: "wa2000_(girls'_frontline)", cn: "WA2000（少女前线）" },
    { en: "wakaba_mutsumi", cn: "若葉睦" },
    { en: "wakamo_(blue_archive)", cn: "和歌子（蔚蓝档案）" },
    { en: "wakasagihime", cn: "若狭姬" },
    { en: "warspite_(kancolle)", cn: "厌战（舰队Collection）" },
    { en: "watanabe_you", cn: "渡边曜" },
    { en: "watatsuki_no_toyohime", cn: "绵月丰姬" },
    { en: "watatsuki_no_yorihime", cn: "绵月依姬" },
    { en: "watson_amelia_(1st_costume)", cn: "沃森·阿米莉亚（第一套服装）" },
    { en: "weiss_schnee", cn: "魏丝·雪倪" },
    { en: "winning_ticket_(umamusume)", cn: "胜利券（赛马娘）" },
    { en: "winry_rockbell", cn: "温莉·洛克贝尔" },
    { en: "wise_(zenless_zone_zero)", cn: "明智（绝区零）" },
    { en: "wo-class_aircraft_carrier", cn: "WO级航空母舰" },
    { en: "wraith_(apex_legends)", cn: "幽灵（Apex英雄）" },
    { en: "xiangling_(genshin_impact)", cn: "香菱（原神）" },
    { en: "xianyun_(genshin_impact)", cn: "闲云（原神）" },
    { en: "xiao_(genshin_impact)", cn: "魈（原神）" },
    { en: "xingqiu_(genshin_impact)", cn: "行秋（原神）" },
    { en: "y'shtola_rhul", cn: "雅·修特拉·如尔" },
    { en: "yae_miko", cn: "八重神子" },
    { en: "yae_sakura", cn: "八重樱" },
    { en: "yahagi_(kancolle)", cn: "矢矧（舰队Collection）" },
    { en: "yamagumo_(kancolle)", cn: "山云（舰队Collection）" },
    { en: "yamakaze_(kancolle)", cn: "山风（舰队Collection）" },
    { en: "yamamura_sadako", cn: "山村贞子" },
    { en: "yamashiro_(azur_lane)", cn: "山城（碧蓝航线）" },
    { en: "yamashiro_(kancolle)", cn: "山城（舰队Collection）" },
    { en: "yamato_(kancolle)", cn: "大和（舰队Collection）" },
    { en: "yamato_(one_piece)", cn: "大和（海贼王）" },
    { en: "yanfei_(genshin_impact)", cn: "烟绯（原神）" },
    { en: "yang_guifei_(fate)", cn: "杨贵妃（Fate）" },
    { en: "yang_xiao_long", cn: "杨小龙" },
    { en: "yaoyorozu_momo", cn: "八百万百" },
    { en: "yasaka_kanako", cn: "八坂神奈子" },
    { en: "yayoi_(kancolle)", cn: "弥生（舰队Collection）" },
    { en: "yelan_(genshin_impact)", cn: "夜兰（原神）" },
    { en: "yin_(darker_than_black)", cn: "银（黑之契约者）" },
    { en: "yoimiya_(genshin_impact)", cn: "宵宫（原神）" },
    { en: "yoisaki_kanade", cn: "宵崎奏" },
    { en: "yoko_littner", cn: "优子·利特纳" },
    { en: "yor_briar", cn: "约尔·布莱尔" },
    { en: "yorigami_jo'on", cn: "依神女苑" },
    { en: "yorigami_shion", cn: "依神紫苑" },
    { en: "yorumi_rena", cn: "夜刃澪奈" },
    { en: "yoshida_yuuko_(machikado_mazoku)", cn: "吉田优子（街角魔族）" },
    { en: "yoshikawa_chinatsu", cn: "吉川千夏" },
    { en: "yoshimi_(blue_archive)", cn: "吉见（蔚蓝档案）" },
    { en: "yoshizawa_kasumi", cn: "吉泽霞" },
    { en: "yowane_haku", cn: "弱音白" },
    { en: "yu_mei-ren_(fate)", cn: "虞美人（Fate）" },
    { en: "yugiri_tsuzuri", cn: "夕雾缀" },
    { en: "yui_(angel_beats!)", cn: "由依（Angel Beats!）" },
    { en: "yui_(princess_connect!)", cn: "优衣（公主连结！）" },
    { en: "yuigahama_yui", cn: "由比滨结衣" },
    { en: "yuki_miku", cn: "雪未来" },
    { en: "yuki_setsuna", cn: "雪之下雪乃" },
    { en: "yukihana_lamy", cn: "雪花拉米" },
    { en: "yukihana_lamy_(1st_costume)", cn: "雪花拉米（第一套服装）" },
    { en: "yukine_chris", cn: "雪音克莉丝" },
    { en: "yukinoshita_yukino", cn: "雪之下雪乃" },
    { en: "yukoku_kiriko", cn: "幽谷雾子" },
    { en: "yumehara_nozomi", cn: "梦原希" },
    { en: "yumemi_riamu", cn: "梦寐里亚姆" },
    { en: "yumi_(senran_kagura)", cn: "弓（闪乱神乐）" },
    { en: "yuna_(ff10)", cn: "尤娜（最终幻想10）" },
    { en: "yuno_(hidamari_sketch)", cn: "由乃（向阳素描）" },
    { en: "yunyun_(konosuba)", cn: "芸芸（为美好的世界献上祝福！）" },
    { en: "yura_(kancolle)", cn: "由良（舰队Collection）" },
    { en: "yuri_(doki_doki_literature_club)", cn: "尤里（心跳文学部）" },
    { en: "yusa_kozue", cn: "遊佐こずえ" },
    { en: "yuubari_(kancolle)", cn: "夕張（舰队Collection）" },
    { en: "yuudachi_kai_ni_(kancolle)", cn: "夕立改二（舰队Collection）" },
    { en: "yuuka_(blue_archive)", cn: "优香（蔚蓝档案）" },
    { en: "yuuka_(track)_(blue_archive)", cn: "优香（田径部）（蔚蓝档案）" },
    { en: "yuuki_(princess_connect!)", cn: "优衣（公主连结！）" },
    { en: "yuuki_(sao)", cn: "桐人（刀剑神域）" },
    { en: "yuuki_mikan", cn: "结城美柑" },
    { en: "yuzu_(blue_archive)", cn: "柚子（蔚蓝档案）" },
    { en: "yuzuki_choco", cn: "柚木千早" },
    { en: "yuzuriha_inori", cn: "楪祈" },
    { en: "z23_(azur_lane)", cn: "Z23（碧蓝航线）" },
    { en: "zara_(azur_lane)", cn: "扎拉（碧蓝航线）" },
    { en: "zara_(kancolle)", cn: "扎拉（舰队Collection）" },
    { en: "zero_two_(darling_in_the_franxx)", cn: "零二（DARLING in the FRANXX）" },
    { en: "zeta_(granblue_fantasy)", cn: "泽塔（碧蓝幻想）" },
    { en: "zhu_yuan", cn: "朱鸢" },
    { en: "ziche_fuzhao", cn: "子车伕鍣" },
    { en: "zidane_tribal", cn: "基达·特利巴尔" },
    { en: "zuihou_(kancolle)", cn: "瑞凤（舰队Collection）" },
    { en: "Gotoh Hitori", cn: "后藤一里波奇酱（孤独摇滚）" },
    { en: "ijichi_nijika", cn: "伊地知虹夏（孤独摇滚）" },
    { en: "Yamada Ryo", cn: "山田凉（孤独摇滚）" },
    { en: "Kita Ikuyo", cn: "喜多郁代（孤独摇滚）" },
];

// 初始化侧边栏内容
document.addEventListener('DOMContentLoaded', () => {
    const sidebar = document.querySelector('.sidebar-content');
    
    // 清空现有内容
    sidebar.innerHTML = '';
    
    // 添加所有提示词
    prompts.forEach(prompt => {
        const item = document.createElement('div');
        item.className = 'sidebar-item';
        item.textContent = prompt.cn;
        
        // 添加点击事件保持原有功能
        item.addEventListener('click', () => {
            const searchInput = document.getElementById('searchInput');
            searchInput.value = prompt.en;
            searchInput.dispatchEvent(new Event('input'));
        });
        
        sidebar.appendChild(item);
    });
});

// 选中的prompt集合
let selectedPrompts = new Set();

// 初始化搜索功能
document.getElementById('searchInput').addEventListener('input', function(e) {
    const searchTerm = e.target.value.toLowerCase();
    const resultsContainer = document.getElementById('results');
    resultsContainer.innerHTML = '';

    if (searchTerm) {
        const filtered = prompts
            .map(prompt => {
                const searchTermLower = searchTerm.toLowerCase();
                const enMatch = prompt.en.toLowerCase().includes(searchTermLower);
                const cnMatch = prompt.cn.toLowerCase().includes(searchTermLower);
                return {
                    score: cnMatch ? 2 : enMatch ? 1 : 0,
                    item: prompt
                };
            })
            .filter(entry => entry.score > 0)
            .sort((a, b) => b.score - a.score)
            .map(entry => entry.item);

        filtered.forEach(prompt => {
            const div = document.createElement('div');
            div.className = `prompt-item ${selectedPrompts.has(prompt) ? 'selected' : ''}`;
            
            // 高亮匹配文本
            const regex = new RegExp(`(${searchTerm})`, 'gi');
            let highlighted = '';
            
            // 优化中文匹配显示
            if (prompt.cn.toLowerCase().includes(searchTerm)) {
                highlighted = prompt.cn.replace(regex, '<span class="highlight">$1</span>');
            } else {
                highlighted = prompt.en.replace(regex, '<span class="highlight">$1</span>');
            }
            
            const item = document.createElement('div');
            item.className = 'result-item';
            
            const text = document.createElement('div');
            text.className = 'result-text';
            text.innerHTML = highlighted;
            text.addEventListener('click', () => togglePrompt(prompt, item));
            
            item.appendChild(text);
            resultsContainer.appendChild(item);
        });
    }
});

// 切换prompt选择状态
function togglePrompt(prompt, element) {
    if (selectedPrompts.has(prompt)) {
        selectedPrompts.delete(prompt);
        element.classList.remove('selected');
    } else {
        selectedPrompts.add(prompt);
        element.classList.add('selected');
    }
    updateOutputBox();
}

// 更新输出框内容
function updateOutputBox() {
    const outputBox = document.getElementById('outputBox');
    outputBox.innerHTML = '';
    
    Array.from(selectedPrompts).forEach(prompt => {
        const item = document.createElement('div');
        item.className = 'output-item';
        
        const text = document.createElement('span');
        text.className = 'output-text';
        text.textContent = prompt.en;
        
        const delBtn = document.createElement('button');
        delBtn.className = 'delete-btn';
        delBtn.textContent = '×';
        delBtn.addEventListener('click', () => {
            selectedPrompts.delete(prompt);
            updateOutputBox();
            // 同时更新搜索结果中的选中状态
            document.querySelectorAll('.prompt-item').forEach(el => {
                if (el.dataset.en === prompt.en) {
                    el.classList.remove('selected');
                }
            });
        });
        
        item.appendChild(text);
        item.appendChild(delBtn);
        outputBox.appendChild(item);
    });
}

// 初始化复制按钮
document.getElementById('copyBtn').addEventListener('click', async () => {
    try {
        const promptsText = Array.from(document.querySelectorAll('.output-text'))
            .map(el => el.textContent)
            .join(', ');
        await navigator.clipboard.writeText(promptsText);
        alert('内容已复制到剪贴板！');
    } catch (err) {
        console.error('复制失败:', err);
    }
});

document.getElementById('clearBtn').addEventListener('click', () => {
    selectedPrompts.clear();
    document.getElementById('outputBox').innerHTML = '';
});